const KEY="MathExamBooster_v1";
let state=load(), page="home",quiz=null,timer=null,flashIndex=0,flashShown=false;
const FORMULAS=[["f1", "พื้นที่วงกลม", "$A=\\pi r^2$", "A=พื้นที่, r=รัศมี", "เมื่อถามพื้นที่วงกลม", "รัศมี 2 ครั้งแล้วคูณ π"], ["f2", "พีทาโกรัส", "$a^2+b^2=c^2$", "c=ด้านตรงข้ามมุมฉาก", "สามเหลี่ยมมุมฉาก", "สองข้างกำลังสองรวม = ด้านยาวกำลังสอง"], ["f3", "ความน่าจะเป็น", "$P(E)=\\frac{สิ่งที่ต้องการ}{ผลลัพธ์ทั้งหมด}$", "E=เหตุการณ์", "เมื่อผลลัพธ์มีโอกาสเท่ากัน", "อยากได้อะไร / มีทั้งหมดเท่าไร"], ["f4", "ผลต่างกำลังสอง", "$a^2-b^2=(a-b)(a+b)$", "a,b=พจน์", "แยกตัวประกอบ", "ลบก่อน บวกทีหลัง"], ["f5", "กฎกำลังอนุพันธ์", "$\\frac{d}{dx}x^n=nx^{n-1}$", "n=เลขชี้กำลัง", "หาอนุพันธ์", "ดึง n ลงหน้าแล้วลด 1"], ["f6", "ค่าเฉลี่ย", "$\\bar{x}=\\frac{\\sum x}{n}$", "n=จำนวนข้อมูล", "โจทย์ค่าเฉลี่ย", "รวมแล้วหารจำนวนตัว"], ["f7", "Det 2×2", "$ad-bc$", "A=[[a,b],[c,d]]", "เมทริกซ์ 2×2", "ทแยงหลักลบทแยงรอง"], ["f8", "คูณเมทริกซ์", "$(m\\times n)(n\\times p)=m\\times p$", "มิติด้านในต้องเท่ากัน", "ตรวจว่าคูณได้หรือไม่", "ในเท่ากัน นอกคือคำตอบ"]];
const TOPICS=[...new Set(QUESTIONS.map(q=>q.topic))];
function load(){let d={attempts:0,correct:0,wrong:[],mistakes:{},formulaKnown:[],review:[],streak:0,last:null,xp:0,level:1,history:[],settings:{name:"",goal:20},examDate:"2026-09-15",prioritySubject:"เมทริกซ์",matrixMistakes:{},matrixHistory:[],matrixSpeed:[]};try{return Object.assign(d,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return d}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function go(p){page=p;render();scrollTo(0,0)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function pct(a,b){return b?Math.round(a/b*100):0}
function active(){let d=new Date().toDateString();if(state.last!==d){let prev=state.last?new Date(state.last):null;if(prev){prev.setHours(0,0,0,0);let now=new Date();now.setHours(0,0,0,0);state.streak=((now-prev)/86400000===1)?state.streak+1:1}else state.streak=1;state.last=d;save()}document.getElementById("streak").textContent="🔥 "+state.streak+" วัน"}
function addXP(x){state.xp+=x;state.level=1+Math.floor(state.xp/500);save()}
function render(){active();let c=document.getElementById("content");if(page==="home")home(c);else if(page==="learn")learn(c);else if(page==="practice")practice(c);else if(page==="memorize")memorize(c);else if(page==="mock")mock(c);else if(page==="last")last(c);else if(page==="progress")progress(c);else if(page==="settings")settings(c);else if(page==="matrix")matrix(c);else if(page==="matrixzero")matrixZero(c);else if(page==="matrixform")matrixForm(c);else if(page==="matrixcrash")matrixCrash(c);else if(page==="matrixrecall")matrixRecall(c);else if(page==="matrixdrill")matrixDrill(c);else if(page==="matrixmock")matrixMock(c);else if(page==="matrixtraps")matrixTraps(c);else if(page==="matrixcheck")matrixCheck(c);else if(page==="quiz")(quiz.mode==="matrixmock"?matrixMockExamView:quizView)(c);else if(page==="matrixresult")matrixResult(c);else if(page==="ai")aiGenerator(c);else if(page==="worked")workedExamples(c);else if(page==="tools")mathTools(c);else if(page==="matrixcalc")matrixCalc(c);document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===page));if(window.MathJax)MathJax.typesetPromise()}

function aiGenerator(c){
 const topics=TOPICS.filter(x=>x!=="เมทริกซ์");
 c.innerHTML=`<div class="hero"><small>🤖 AI QUESTION GENERATOR</small><h1>สร้างโจทย์ใหม่ด้วย AI</h1><p>สร้างโจทย์นอกเหนือจาก Question Bank และตรวจว่า Answer ตรงกับ Choice ก่อนนำไปทำ Quiz</p></div>
 <div class="card" style="margin-top:18px"><div class="grid choicegrid">
 <label>บท<select id="aiTopic"><option>เมทริกซ์</option>${topics.map(x=>`<option>${esc(x)}</option>`).join("")}</select></label>
 <label>หัวข้อ<input id="aiSub" value="Matrix Multiplication" placeholder="เช่น Determinant, Inverse"></label>
 <label>แนวโจทย์<select id="aiStyle"><option value="mixed">ผสม</option><option value="theory" selected>🧠 ทฤษฎีเป็นหลัก (80%)</option><option value="theory90">📚 ทฤษฎีเข้ม (90%)</option><option value="calc">📐 คำนวณเป็นหลัก</option></select></label>
 <label>ระดับ<select id="aiDiff"><option>ง่าย</option><option selected>กลาง</option><option>ยาก</option></select></label>
 <label>จำนวน<select id="aiCount"><option>5</option><option selected>10</option><option>20</option></select></label>
 </div>
 <label style="display:block;margin-top:12px">คำสั่งเพิ่มเติม<textarea id="aiPrompt" rows="3" placeholder="เช่น เน้นโจทย์หลอกเรื่องเครื่องหมาย และอย่าให้ซ้ำกับ Bank"></textarea></label>
 <div class="actions"><button class="primary" onclick="generateAIQuestions()">✨ Generate โจทย์ใหม่</button><button class="secondary" onclick="aiLocalDemo()">🧪 ทดลองแบบไม่ใช้ API</button></div>
 <div id="aiStatus" class="muted" style="margin-top:12px">AI Mode ต้องมี Backend ที่ตั้งค่า OPENAI_API_KEY</div></div>
 <div id="aiResults" style="margin-top:18px"></div>`;
}
async function generateAIQuestions(){
 const topic=document.getElementById('aiTopic').value,sub=document.getElementById('aiSub').value||topic,difficulty=document.getElementById('aiDiff').value,count=+document.getElementById('aiCount').value,extra=document.getElementById('aiPrompt').value,style=document.getElementById('aiStyle').value;
 const status=document.getElementById('aiStatus'),out=document.getElementById('aiResults');
 status.textContent='⏳ AI กำลังสร้างและตรวจโจทย์...';out.innerHTML='';
 try{
  const r=await fetch('/api/generate-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,subtopic:sub,difficulty,count,extra,style,bank:QUESTIONS.map(q=>({question:q.question,choices:q.choices,answer:q.answer}))})});
  const data=await r.json();if(!r.ok)throw new Error(data.error||'Generate ไม่สำเร็จ');
  const qs=(data.questions||[]).map((q,i)=>({...q,id:`AI-${Date.now()}-${i}`,source:'AI'}));
  window.aiQuestions=qs;status.textContent=`✅ สร้างสำเร็จ ${qs.length} ข้อ — ตรวจ Answer ↔ Choice แล้ว`;
  out.innerHTML=`<div class="card"><div class="head"><h2>🤖 AI Questions</h2><button class="primary" onclick="startAIQuiz()">เริ่มทำชุดนี้ →</button></div>${qs.map((q,i)=>`<div class="listitem"><div><span class="tag">${q.difficulty||difficulty}</span><b>ข้อ ${i+1}</b><div>${esc(q.question)}</div><div class="muted">เฉลย: ${esc(q.answer)}</div></div></div>`).join('')}</div>`;
  if(window.MathJax)MathJax.typesetPromise();
 }catch(e){status.textContent='❌ '+e.message+' — ตรวจว่าเปิด server และตั้ง OPENAI_API_KEY แล้ว';}
}
function startAIQuiz(){if(!window.aiQuestions?.length){toast('ยังไม่มีโจทย์ AI');return}quiz={mode:'ai',pool:window.aiQuestions,i:0,selected:null,answered:false,score:0,seconds:0};go('quiz')}
function aiLocalDemo(){
 const theory=Array.isArray(MATRIX_THEORY_QUESTIONS)?MATRIX_THEORY_QUESTIONS:[];
 const pool=theory.length?theory:matrixQuestions();
 window.aiQuestions=shuffle(pool).slice(0,Math.min(10,pool.length)).map((q,i)=>({...q,id:`LOCAL-AI-${Date.now()}-${i}`,source:'AI-Theory-Demo'}));
 document.getElementById('aiStatus').textContent=`🧠 Theory Demo: ${window.aiQuestions.length} ข้อ — เน้นนิยาม ศัพท์ สมบัติ และเงื่อนไข ไม่เน้นคำนวณ`;
 document.getElementById('aiResults').innerHTML=`<div class="card"><div class="head"><h2>🧠 Theory-First Questions</h2><button class="primary" onclick="startAIQuiz()">เริ่มทำ →</button></div>${window.aiQuestions.map((q,i)=>`<div class="listitem"><div><b>ข้อ ${i+1}</b> <span class="tag">${esc(q.subtopic)}</span><div>${esc(q.question)}</div><div class="muted">ตัวอย่างเฉลย: ${esc(q.answer)}</div></div></div>`).join('')}</div>`;
 if(window.MathJax)MathJax.typesetPromise();
}

function matrixQuestions(){return QUESTIONS.filter(q=>q.topic==="เมทริกซ์")}
function matrixMetrics(){
  const qs=matrixQuestions(), at=state.attemptsMatrix||0, co=state.correctMatrix||0, acc=pct(co,at);
  const fm=pct((state.formulaKnown||[]).filter(x=>MATRIX_FORMULAS.some(f=>f[0]===x)).length,MATRIX_FORMULAS.length);
  const speed=state.matrixSpeed?.length?Math.round(state.matrixSpeed.reduce((a,b)=>a+b,0)/state.matrixSpeed.length):72;
  const concept=Math.min(100,Math.round(acc*.55+fm*.45)||0);
  const readiness=Math.round(concept*.3+fm*.2+acc*.25+speed*.25);
  return {concept,formula:fm,calculation:Math.min(100,acc+5),speed,accuracy:acc,readiness};
}
const MATRIX_FORMULAS=[
 ["mf1","ขนาดเมทริกซ์","m×n","m=แถว, n=หลัก","บอกจำนวนแถวและหลัก","แถว × หลัก"],
 ["mf2","การบวก/ลบ","A±B=[aᵢⱼ±bᵢⱼ]","สมาชิกตำแหน่งเดียวกัน","A และ B ต้องขนาดเท่ากัน","ช่องตรงกันทำไปทีละช่อง"],
 ["mf3","การคูณเมทริกซ์","(m×n)(n×p)=m×p","มิติของ A และ B","ด้านในต้องเท่ากัน","ในต้องเท่ากัน นอกเอาไปตอบ"],
 ["mf4","Transpose","Aᵀ: แถว ↔ หลัก","สลับตำแหน่งแถว/หลัก","ใช้เมื่อโจทย์ถาม transpose","แถวกลายเป็นหลัก"],
 ["mf5","Det 2×2","det(A)=ad−bc","A=[[a,b],[c,d]]","เมทริกซ์ 2×2","ทแยงหลักลบทแยงรอง"],
 ["mf6","Det 3×3","a(ei−fh)−b(di−fg)+c(dh−eg)","a...i คือสมาชิก 3×3","ใช้ขยายตามแถวแรก","เครื่องหมาย + − +"],
 ["mf7","Inverse 2×2","A⁻¹=1/(ad−bc)[[d,−b],[−c,a]]","det(A)≠0","หา inverse ของ 2×2","สลับมุม เปลี่ยนเครื่องหมายตัวกลาง แล้วหาร det"],
 ["mf8","Adjoint","adj(A)=Cᵀ","C=cofactor matrix","ใช้ร่วมกับสูตร inverse","หา Cofactor แล้ว transpose"],
 ["mf9","Inverse ทั่วไป","A⁻¹=1/det(A) · adj(A)","det(A)≠0","หา inverse เมื่อมี adjoint","det ไม่เป็นศูนย์"],
 ["mf10","Cramer","xᵢ=Dᵢ/D","D=det coefficient matrix","แก้ระบบสมการเมื่อ D≠0","หาตัว D ก่อน แล้วค่อย Dx/Dy"]
];
function matrixStatus(r){return r>=80?"🟢 พร้อมสอบ":r>=60?"🟡 ควรทบทวนบางหัวข้อ":"🔴 ต้องเร่งติว"}
function matrix(c){
 const m=matrixMetrics(), weak=Object.entries(state.matrixMistakes||{}).sort((a,b)=>b[1]-a[1]).slice(0,3);
 c.innerHTML=`<div class="hero"><small>🔥 MATRIX EXAM BOOST</small><h1>ติวเมทริกซ์ก่อนสอบแบบเร่งด่วน</h1><p>เข้าใจ Concept → จำสูตร → ทำโจทย์ → วิเคราะห์ข้อผิด → ทำซ้ำ → จับเวลา</p><div class="actions"><button class="primary" onclick="go('matrixzero')">🧠 เริ่มเรียน Matrix จาก 0</button><button class="secondary" onclick="go('matrixcrash')">🚀 Matrix Crash Course</button><button class="secondary" onclick="go('matrixdrill')">⚡ 5 นาที Matrix Drill</button></div></div>
 <div class="card" style="margin-top:18px"><div class="head"><h2>MATRIX EXAM READINESS</h2><b>${m.readiness}%</b></div><div class="bar"><i style="width:${m.readiness}%"></i></div><p>${matrixStatus(m.readiness)}</p></div>
 <div class="grid stats"><div class="card"><div class="muted">🧠 Concept</div><div class="num">${m.concept}%</div></div><div class="card"><div class="muted">📚 Formula</div><div class="num">${m.formula}%</div></div><div class="card"><div class="muted">📐 Calculation</div><div class="num">${m.calculation}%</div></div><div class="card"><div class="muted">⚡ Speed</div><div class="num">${m.speed}%</div></div><div class="card"><div class="muted">🎯 Accuracy</div><div class="num">${m.accuracy}%</div></div><div class="card"><div class="muted">❌ ผิดสะสม</div><div class="num">${(state.wrongMatrix||[]).length}</div></div></div>
 <div class="head"><h2>📚 Matrix Roadmap</h2></div><div class="grid topics">${["พื้นฐาน & ขนาด","Addition / Subtraction","Scalar","Multiplication","Transpose","Determinant 2×2 / 3×3","Minor / Cofactor / Adjoint","Inverse","ระบบสมการ","Cramer's Rule"].map((x,i)=>`<div class="card"><span class="tag">${i<6?"🔥 ออกสอบบ่อย":"⭐ ควรรู้"}</span><h3>${x}</h3><p class="muted">เข้าใจสั้น → จำ → ทำโจทย์</p><button class="secondary" onclick="matrixTopic('${x}')">ฝึกหัวข้อนี้</button></div>`).join("")}</div>
 <div class="head"><h2>🚨 TOP 3 เรื่องที่ต้องทบทวน</h2></div><div class="list">${weak.length?weak.map(x=>`<div class="listitem"><b>${x[0]}</b><span>${x[1]} ครั้ง</span><button class="secondary" onclick="matrixTopic('${x[0]}')">ทบทวน</button></div>`).join(""):'<div class="card">ยังไม่มีข้อมูลผิด — เริ่มทำโจทย์เพื่อให้ระบบวิเคราะห์</div>'}</div>
 <div class="head"><h2>🧰 Matrix Tools</h2><div class="muted">ทุกเครื่องมือของเมทริกซ์อยู่ในหน้านี้</div></div><div class="matrix-menu-grid"><button class="card menu-card" onclick="go('matrixzero')">🧠<b>เรียน Matrix จาก 0</b><small>ปูพื้นฐานทีละขั้น</small></button><button class="card menu-card" onclick="go('matrixform')">📖<b>Formula Cheat Sheet</b><small>สูตรที่ต้องจำ</small></button><button class="card menu-card" onclick="go('matrixcalc')">🧮<b>Matrix Calculator</b><small>det · inverse · transpose</small></button><button class="card menu-card" onclick="go('matrixrecall')">🔁<b>Active Recall</b><small>ฝึกจำเร็ว</small></button><button class="card menu-card" onclick="go('matrixdrill')">⚡<b>5 นาที Drill</b><small>จับเวลา</small></button><button class="card menu-card" onclick="go('matrixmock')">🎯<b>Mock Exam</b><small>จำลองสอบ</small></button><button class="card menu-card" onclick="go('matrixtraps')">⚠️<b>Matrix Traps</b><small>จุดหลอก</small></button><button class="card menu-card" onclick="go('matrixcheck')">☑️<b>Exam Checklist</b><small>เช็กก่อนสอบ</small></button></div>`;
}
function matrixTopic(t){let map={"พื้นฐาน & ขนาด":"Matrix Basic","Addition / Subtraction":"Addition/Subtraction","Scalar":"Scalar Multiplication","Multiplication":"Matrix Multiplication","Transpose":"Transpose","Determinant 2×2 / 3×3":"Determinant","Minor / Cofactor / Adjoint":"Adjoint","Inverse":"Inverse","ระบบสมการ":"Cramer's Rule","Cramer's Rule":"Cramer's Rule"};let pool=matrixQuestions().filter(q=>(q.subtopic||q.topic)===map[t]||q.topic===map[t]);if(!pool.length)pool=matrixQuestions();quiz={mode:"matrix",pool:shuffle(pool).slice(0,8),i:0,selected:null,answered:false,score:0,seconds:0};go("quiz")}
function matrixForm(c){c.innerHTML=`<div class="head"><div><h2>🧠 MATRIX FORMULA CHEAT SHEET</h2><div class="muted">สูตรที่ควรจำก่อนเข้าห้องสอบ</div></div><button class="secondary" onclick="go('matrix')">← Matrix Dashboard</button></div><div class="list">${MATRIX_FORMULAS.map(f=>`<div class="card"><span class="tag">ต้องจำ</span><h3>${f[1]}</h3><div class="formul">${f[2]}</div><p><b>ความหมาย:</b> ${f[3]}</p><p><b>ใช้เมื่อ:</b> ${f[4]}</p><p>🧠 <b>Memory Trick:</b> ${f[5]}</p><button class="secondary" onclick="mark('${f[0]}')">${state.formulaKnown.includes(f[0])?"⭐ จำแล้ว":"☆ จำแล้ว"}</button></div>`).join("")}</div>`}
function matrixCrash(c){const steps=[["1","รู้จัก Matrix","Matrix คือการจัดตัวเลขเป็นตาราง","matrixTopic('Matrix Basic')"],["2","ขนาดและชนิด","อ่านแถว × หลักให้คล่อง","matrixTopic('พื้นฐาน & ขนาด')"],["3","บวก / ลบ / Scalar","ทำสมาชิกตำแหน่งเดียวกัน","matrixTopic('Addition / Subtraction')"],["4","Matrix Multiplication","ในต้องเท่ากัน นอกเอาไปตอบ","matrixTopic('Multiplication')"],["5","Transpose","แถวกลายเป็นหลัก","matrixTopic('Transpose')"],["6","Determinant","ad−bc และ 3×3","matrixTopic('Determinant 2×2 / 3×3')"],["7","Inverse","สลับมุม เปลี่ยนเครื่องหมายกลาง หาร det","matrixTopic('Inverse')"],["8","ระบบสมการ","เชื่อม Matrix กับการแก้สมการ","matrixTopic('ระบบสมการ')"],["9","ข้อสอบออกบ่อย","ฝึกข้อที่มี trap","go('matrixtraps')"],["10","Mock Exam","20 ข้อ / 30 นาที","go('matrixmock')"]];c.innerHTML=`<div class="head"><div><h2>🔥 MATRIX CRASH COURSE</h2><div class="muted">ไม่ต้องอ่านยาว — ทำตามเส้นทางนี้</div></div></div><div class="list">${steps.map(s=>`<div class="listitem"><div><span class="tag">STEP ${s[0]}</span><b>${s[1]}</b><div class="muted">${s[2]}</div></div><button class="primary" onclick="${s[3]}">เริ่ม</button></div>`).join("")}</div>`}
function matrixRecall(c){const qs=[["Matrix 2×3 หมายถึงอะไร?","มี 2 แถว 3 หลัก"],["A 2×3 และ B 3×4 แล้ว AB มีขนาดเท่าไร?","2×4"],["AB คูณได้เมื่อใด?","จำนวนหลักของ A = จำนวนแถวของ B"],["สูตร det 2×2 คืออะไร?","ad−bc"],["ถ้า det(A)=0 หา A⁻¹ ได้หรือไม่?","ไม่ได้"],["Transpose คืออะไร?","แถวกลายเป็นหลัก และหลักกลายเป็นแถว"],["AB = BA เสมอหรือไม่?","ไม่เสมอ"],["3×2 คูณ 2×4 ผลลัพธ์มีขนาดเท่าไร?","3×4"]];let i=state.matrixRecallIndex||0;let q=qs[i%qs.length];c.innerHTML=`<div class="card flash"><div><span class="tag">ACTIVE RECALL ${i+1}/${qs.length}</span><div class="flashq">${q[0]}</div><div id="mranswer" class="answer" style="display:none">${q[1]}</div><div class="actions" style="justify-content:center"><button class="primary" onclick="document.getElementById('mranswer').style.display='block'">แสดงคำตอบ</button><button class="secondary" onclick="state.matrixRecallIndex=${(i+1)%qs.length};save();matrixRecall(document.getElementById('content'))">ต่อข้อ →</button></div></div></div>`}
function matrixDrill(c){c.innerHTML=`<div class="hero"><small>⚡ 5 MINUTES MATRIX DRILL</small><h1>10 ข้อ / 5 นาที</h1><p>ขนาด → บวก/ลบ → คูณ → Determinant → Inverse → Transpose</p><button class="primary" onclick="startMatrixDrill()">เริ่มจับเวลา 5 นาที</button></div><div class="card" style="margin-top:18px"><b>เกณฑ์แนะนำ</b><p class="muted">8–10 ถูก = ดีมาก · 6–7 = ควรทบทวน · ต่ำกว่า 6 = กลับไป Crash Course</p></div>`}
function startMatrixDrill(){quiz={mode:"matrixdrill",pool:shuffle(matrixQuestions()).slice(0,10),i:0,selected:null,answered:false,score:0,seconds:300,startTime:Date.now()};go("quiz")}
function matrixMock(c){c.innerHTML=`<div class="hero"><small>🎯 MATRIX MOCK EXAM</small><h1>20 ข้อ / 30 นาที</h1><p>สอบจริงแบบเต็มรูปแบบ · Navigator · ทำ/ยังไม่ทำ · ส่งข้อสอบ · เฉลยละเอียดหลังสอบ</p><button class="primary" onclick="startMatrixMock()">🚀 เริ่มสอบ</button></div><div class="head"><h2>ประวัติ Matrix Mock</h2></div>${(state.matrixHistory||[]).length?`<table class="table"><tr><th>วันที่</th><th>คะแนน</th><th>%</th></tr>${state.matrixHistory.slice(-8).reverse().map(x=>`<tr><td>${x.date}</td><td>${x.score}/20</td><td>${x.pct}%</td></tr>`).join("")}</table>`:"<div class='empty'>ยังไม่มีประวัติ</div>"}`}
function startMatrixMock(){let groups=["Matrix Basic","Addition/Subtraction","Scalar Multiplication","Matrix Multiplication","Transpose","Determinant","Inverse","Cramer\'s Rule"];let p=[];groups.forEach((g,i)=>{let n=[2,2,1,4,2,4,3,2][i];p.push(...shuffle(matrixQuestions().filter(q=>q.topic===g)).slice(0,n))});let bank=matrixQuestions();if(p.length<20)p.push(...shuffle(bank.filter(q=>!p.includes(q))));quiz={mode:"matrixmock",pool:shuffle(p).slice(0,20),i:0,answers:Array(20).fill(null),seconds:1800,startTime:Date.now(),startStamp:Date.now(),endTime:Date.now()+1800000};go("quiz")}
function matrixTraps(c){const traps=["Matrix บวก/ลบได้เมื่อขนาดเท่ากัน","AB ไม่จำเป็นต้องเท่ากับ BA","คูณ Matrix ต้องตรวจจำนวนหลักของ A กับจำนวนแถวของ B","det(A)=0 → ไม่มี Inverse","Cofactor ระวังเครื่องหมาย + − +","Transpose ไม่ใช่ Inverse","ตรวจขนาด Matrix ก่อนคูณทุกครั้ง","Inverse 2×2 ต้องสลับ a,d และเปลี่ยนเครื่องหมาย b,c"];c.innerHTML=`<div class="head"><h2>⚠️ MATRIX TRAPS</h2><div class="muted">จุดหลอกที่ควรเห็นแล้วไม่พลาด</div></div><div class="list">${traps.map((x,i)=>`<div class="card"><span class="tag">TRAP ${i+1}</span><h3>${x}</h3><button class="secondary" onclick="trapRecall('${encodeURIComponent(x)}')">🧠 ทดสอบตัวเอง</button></div>`).join("")}</div>`}
function trapRecall(x){let t=decodeURIComponent(x);quiz={mode:"matrix",pool:[{id:"TRAP",topic:"เมทริกซ์",subtopic:"Matrix Traps",difficulty:"กลาง",question:"จริงหรือไม่? "+t,choices:["จริง","ไม่จริง","ขึ้นกับโจทย์","จำไม่ได้"],answer:"จริง",explanation:"หลักนี้เป็นจุดที่มักหลอกในการสอบเมทริกซ์",hint:"นึกถึงกฎพื้นฐานของ Matrix",shortcut:"จำเป็น checklist",commonMistake:"ตอบตามความเคยชิน",tags:["#matrix-traps"],examFrequency:100}],i:0,selected:null,answered:false,score:0,seconds:0};go("quiz")}
function matrixCheck(c){const items=["รู้ความหมายของ Matrix","อ่านขนาด Matrix ได้","บวก Matrix ได้","ลบ Matrix ได้","คูณ Scalar ได้","คูณ Matrix ได้","หา Transpose ได้","หา Determinant 2×2 ได้","หา Determinant 3×3 ได้","หา Inverse ได้","รู้เงื่อนไขการมี Inverse","แก้ระบบสมการได้","รู้ Cramer's Rule","ทำโจทย์จับเวลาได้"];let done=state.matrixChecklist||[];let count=done.length;c.innerHTML=`<div class="head"><div><h2>☑️ MATRIX MUST-KNOW CHECKLIST</h2><div class="muted">เช็กสิ่งที่ต้องรู้ก่อนเข้าห้องสอบ</div></div><b>${count}/${items.length}</b></div><div class="bar"><i style="width:${pct(count,items.length)}%"></i></div><div class="list" style="margin-top:15px">${items.map((x,i)=>`<label class="listitem"><span><input type="checkbox" ${done.includes(i)?"checked":""} onchange="toggleMatrixCheck(${i},this.checked)"> ${x}</span></label>`).join("")}</div>${count===items.length?`<div class="card" style="margin-top:15px;text-align:center"><h2>🎯 MATRIX READY</h2><p>คุณพร้อมเข้าสอบเมทริกซ์แล้ว</p></div>`:""}`}
function toggleMatrixCheck(i,on){state.matrixChecklist=state.matrixChecklist||[];if(on&&!state.matrixChecklist.includes(i))state.matrixChecklist.push(i);if(!on)state.matrixChecklist=state.matrixChecklist.filter(x=>x!==i);save();render()}
function matrixMockExamView(c){clearInterval(timer);let q=quiz.pool[quiz.i],ans=quiz.answers[quiz.i],done=quiz.answers.filter(x=>x!==null).length;let nav=quiz.pool.map((_,i)=>`<button class="mock-nav ${i===quiz.i?'current':''} ${quiz.answers[i]!==null?'done':''}" onclick="jumpMatrixMock(${i})">${i+1}</button>`).join("");c.innerHTML=`<div class="mock-exam-head"><div><small>🎯 MATRIX MOCK EXAM</small><h2>ข้อ ${quiz.i+1} / ${quiz.pool.length}</h2><div class="muted">ทำแล้ว ${done}/20 · ยังไม่ทำ ${20-done}</div></div><div class="mock-clock" id="clock">30:00</div></div><div class="mock-layout"><aside class="mock-sidebar"><b>📋 Navigator</b><div class="mock-nav-grid">${nav}</div><div class="mock-legend"><span><i class="legend-dot done-dot"></i>ทำแล้ว</span><span><i class="legend-dot"></i>ยังไม่ทำ</span></div><button class="danger full" onclick="finishMatrixMock(true)">📤 ส่งข้อสอบ</button></aside><main class="mock-question"><div class="tag">${q.subtopic||q.topic}</div><div class="q">${q.question}</div><div class="choices">${q.choices.map((x,i)=>`<button class="choice ${ans===i?'sel':''}" onclick="selectMatrixMock(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join("")}</div><div class="mock-actions"><button class="secondary" onclick="jumpMatrixMock(${Math.max(0,quiz.i-1)})" ${quiz.i===0?'disabled':''}>← ก่อนหน้า</button><button class="primary" onclick="jumpMatrixMock(${Math.min(quiz.pool.length-1,quiz.i+1)})" ${quiz.i===quiz.pool.length-1?'disabled':''}>ข้อถัดไป →</button></div><div class="mock-bottom"><button class="secondary" onclick="finishMatrixMock(true)">📤 ส่งข้อสอบ</button><span class="muted">เมื่อส่งแล้วจะดูคะแนนและเฉลยละเอียดได้ทันที</span></div></main></div>`;startTimer()}
function selectMatrixMock(i){quiz.answers[quiz.i]=i;matrixMockExamView(document.getElementById("content"))}
function jumpMatrixMock(i){quiz.i=Math.max(0,Math.min(quiz.pool.length-1,i));matrixMockExamView(document.getElementById("content"))}
function finishMatrixMock(force){let unanswered=quiz.answers.filter(x=>x===null).length;if(unanswered&&force&&!confirm(`ยังไม่ได้ทำ ${unanswered} ข้อ\nต้องการส่งข้อสอบเลยหรือไม่?`))return;clearInterval(timer);let score=0;quiz.answers.forEach((a,i)=>{if(a!==null&&quiz.pool[i].choices[a]===quiz.pool[i].answer)score++});quiz.score=score;let review=quiz.pool.map((q,i)=>({q:q,selected:quiz.answers[i],selectedAnswer:quiz.answers[i]===null?null:q.choices[quiz.answers[i]],correct:q.answer,isCorrect:quiz.answers[i]!==null&&q.choices[quiz.answers[i]]===q.answer}));state.matrixHistory=state.matrixHistory||[];state.matrixHistory.push({date:new Date().toLocaleString("th-TH"),score,pct:pct(score,quiz.pool.length)});state.matrixLastReview=review;state.attemptsMatrix=(state.attemptsMatrix||0)+quiz.pool.length;state.correctMatrix=(state.correctMatrix||0)+score;review.forEach(r=>{state.attempts++;if(r.isCorrect){state.correct++;}else if(r.q.id){if(!state.wrong.includes(r.q.id))state.wrong.push(r.q.id);state.mistakes[r.q.topic]=(state.mistakes[r.q.topic]||0)+1;state.wrongMatrix=state.wrongMatrix||[];if(!state.wrongMatrix.includes(r.q.id))state.wrongMatrix.push(r.q.id)}});save();go("matrixresult")}
function matrixResult(c){let last=state.matrixHistory?.[state.matrixHistory.length-1],review=state.matrixLastReview||[],correct=review.filter(x=>x.isCorrect).length,answered=review.filter(x=>x.selected!==null).length,unanswered=20-answered;let details=review.map((r,i)=>`<div class="review-card ${r.isCorrect?'review-ok':'review-bad'}"><div class="review-title"><b>ข้อ ${i+1}</b><span>${r.isCorrect?'✓ ถูก':'✗ ผิด/ไม่ตอบ'}</span></div><div class="q">${r.q.question}</div><div class="muted">คำตอบของคุณ: <b>${r.selectedAnswer===null?'ไม่ได้ตอบ':esc(r.selectedAnswer)}</b> · เฉลย: <b>${esc(r.correct)}</b></div><div class="solution"><b>📖 วิธีทำละเอียด</b><br>${matrixDetailedSolution(r.q)||r.q.explanation||'วิเคราะห์นิยาม เงื่อนไข และคำนวณทีละขั้น'}<br><b>💡 วิธีคิด:</b> ${r.q.hint||'ตรวจเงื่อนไขก่อนคำนวณ'}<br><b>⚠️ จุดที่มักผิด:</b> ${r.q.commonMistake||'ตรวจเครื่องหมายและลำดับการคำนวณ'}</div></div>`).join("");c.innerHTML=`<div class="hero"><small>🎯 MATRIX MOCK RESULT</small><h1>${last?.score||correct}/20 · ${last?.pct||pct(correct,20)}%</h1><p>${unanswered?`ไม่ได้ตอบ ${unanswered} ข้อ · `:''}${matrixStatus(matrixMetrics().readiness)} · ด้านล่างคือเฉลยละเอียดทั้งชุด</p></div><div class="grid stats"><div class="card"><div class="muted">คะแนน</div><div class="num">${correct}/20</div></div><div class="card"><div class="muted">Accuracy</div><div class="num">${pct(correct,20)}%</div></div><div class="card"><div class="muted">ทำแล้ว</div><div class="num">${answered}/20</div></div><div class="card"><div class="muted">ยังไม่ตอบ</div><div class="num">${unanswered}</div></div></div><div class="actions"><button class="primary" onclick="startMatrixMock()">🔄 สอบอีกครั้ง</button><button class="secondary" onclick="go('matrix')">กลับ Matrix Dashboard</button></div><div class="head"><h2>📖 เฉลยละเอียด 20 ข้อ</h2><div class="muted">ทบทวนข้อผิดก่อน แล้วค่อยกลับไปสอบใหม่</div></div><div class="review-list">${details}</div>`}
function home(c){let acc=pct(state.correct,state.attempts),ready=Math.round(acc*.4+pct(state.formulaKnown.length,FORMULAS.length)*.25+Math.min(100,state.attempts/30*100)*.2+Math.min(100,TOPICS.length)*.15);let weak=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1])[0]?.[0]||"ยังไม่มีข้อมูล";c.innerHTML=`<div class="hero"><div><small>🔥 YOUR NEXT EXAM · MATRIX · VERY HIGH PRIORITY</small><h1>พร้อมสอบคณิตแค่ไหน?</h1><p>ไม่ต้องอ่านทุกอย่าง เลือกสิ่งที่ต้องรู้ ทำสิ่งที่ต้องทำ จำสิ่งที่ต้องจำ แล้วเข้าห้องสอบอย่างมั่นใจ</p><div class="card" style="margin:15px 0;background:#ffffff14;border-color:#ffffff25"><b>📅 สอบเมทริกซ์: วันอังคาร</b> · <span id="examCountdown">กำลังคำนวณ...</span><br><small>วันนี้ควรโฟกัส: Matrix Multiplication → Determinant → Inverse → Timed Drill</small></div><div class="actions"><button class="primary" onclick="go('practice')">🚀 เริ่มติว</button><button class="secondary" onclick="go('last')">⚡ ติวด่วนก่อนสอบ</button></div></div></div><div class="grid stats"><div class="card"><div class="muted">ความพร้อมสอบ</div><div class="num">${ready}%</div><div class="bar"><i style="width:${ready}%"></i></div></div><div class="card"><div class="muted">โจทย์ที่ทำ</div><div class="num">${state.attempts}</div><div class="muted">ถูก ${state.correct} ข้อ</div></div><div class="card"><div class="muted">สูตรที่จำได้</div><div class="num">${state.formulaKnown.length}/${FORMULAS.length}</div></div><div class="card"><div class="muted">จุดอ่อน</div><div class="num">${weak}</div></div></div><div class="head"><h2>วันนี้ควรทำอะไร</h2></div><div class="grid quick">${[["📚","ทบทวน Concept","learn"],["✏️","ทำโจทย์ 10 ข้อ","practice"],["🧠","ฝึกจำสูตร","memorize"],["⚡","Mini Test","practice"],["🎯","Mock Exam","mock"]].map(x=>`<button class="card" onclick="go('${x[2]}')"><div class="emoji">${x[0]}</div><b>${x[1]}</b><div class="muted">เริ่มได้ทันที</div></button>`).join("")}</div><div class="head"><h2>🔥 โฟกัสก่อนสอบ</h2></div><div class="grid topics">${TOPICS.slice(0,6).map(t=>`<div class="card"><span class="tag">#ออกสอบบ่อย</span><h3>${t}</h3><p class="muted">เข้าใจ 60 วิ → สูตร → ตัวอย่าง → ลองทำ</p><button class="secondary" onclick="startTopic('${t}')">เริ่มติว</button></div>`).join("")}</div>`;setTimeout(()=>{const e=document.getElementById('examCountdown');if(e){const d=state.examDate?new Date(state.examDate+'T09:00:00'):new Date('2026-09-15T09:00:00');const days=Math.max(0,Math.ceil((d-new Date())/86400000));e.textContent=days===0?'สอบวันนี้!':`เหลือ ${days} วัน`;}});}
function learn(c){c.innerHTML=`<div class="head"><div><h2>📚 Learn</h2><div class="muted">ติวสั้น ไม่ใช่อ่านตำรายาว ๆ</div></div></div><div class="grid topics">${TOPICS.map((t,i)=>`<div class="card"><span class="tag">${i<8?"🔥 ออกสอบบ่อย":"บทเรียน"}</span><h3>${t}</h3><p class="muted">① เข้าใจใน 60 วินาที<br>② สูตรที่ต้องจำ<br>③ วิธีสังเกตโจทย์<br>④ ลองทำเอง<br>⑤ สรุปก่อนสอบ</p><button class="primary" onclick="startTopic('${t}')">🚀 ติวบทนี้</button></div>`).join("")}</div>`}
function startTopic(t){quiz={mode:"practice",pool:shuffle(QUESTIONS.filter(q=>q.topic===t)).slice(0,5),i:0,selected:null,answered:false,score:0,seconds:0};go("quiz")}
function practice(c){let wrong=state.wrong.map(id=>QUESTIONS.find(q=>q.id===id)).filter(Boolean);c.innerHTML=`<div class="head"><div><h2>✏️ Practice</h2><div class="muted">ทำจริง + Hint + วิเคราะห์ข้อผิด</div></div></div><div class="card"><div class="grid choicegrid"><label>บท<select id="pt">${`<option value="all">ทุกบท</option>`+TOPICS.map(t=>`<option>${t}</option>`).join("")}</select></label><label>ระดับ<select id="pd"><option value="all">ผสม</option><option>ง่าย</option><option>กลาง</option><option>ยาก</option></select></label><label>จำนวน<select id="pc"><option>5</option><option selected>10</option><option>20</option><option>50</option></select></label><label>เวลา<select id="tm"><option value="0">ไม่จับเวลา</option><option value="5">5 นาที</option><option value="10">10 นาที</option><option value="20">20 นาที</option></select></label></div><div class="actions" style="margin-top:16px"><button class="primary" onclick="startPractice()">🚀 เริ่มทำ</button><button class="secondary" onclick="retryWrong()">❌ ทำข้อที่เคยผิด</button></div></div><div class="head"><h2>❌ Wrong Questions (${wrong.length})</h2></div><div class="list">${wrong.slice(-10).reverse().map(q=>`<div class="listitem"><div><b>${q.question}</b><div class="muted">${q.topic} · ${q.difficulty}</div></div><button class="secondary" onclick="one('${q.id}')">ทำใหม่</button></div>`).join("")||'<div class="empty">ยังไม่มีข้อผิด</div>'}</div>`}
function startPractice(){let t=document.getElementById("pt").value,d=document.getElementById("pd").value,n=+document.getElementById("pc").value,sec=+document.getElementById("tm").value*60;let p=QUESTIONS.filter(q=>(t==="all"||q.topic===t)&&(d==="all"||q.difficulty===d));quiz={mode:"practice",pool:shuffle(p.length?p:QUESTIONS).slice(0,n),i:0,selected:null,answered:false,score:0,seconds:sec};go("quiz")}
function retryWrong(){let p=shuffle(QUESTIONS.filter(q=>state.wrong.includes(q.id)));if(!p.length){toast("ยังไม่มีข้อผิด");return}quiz={mode:"practice",pool:p.slice(0,10),i:0,selected:null,answered:false,score:0,seconds:600};go("quiz")}
function one(id){let q=QUESTIONS.find(x=>x.id===id);quiz={mode:"practice",pool:[q],i:0,selected:null,answered:false,score:0,seconds:0};go("quiz")}


const WORKED_EXAMPLES=[
 ['Matrix Basic','อ่านสมาชิก','กำหนด A=[[2, -1, 4],[0, 3, 5]] แล้ว a₂₃ เท่ากับเท่าไร?','5','1) A มี 2 แถว 3 หลัก\n2) a₂₃ = แถวที่ 2 หลักที่ 3\n3) ดูสมาชิกตำแหน่งนั้น → 5\n4) ดังนั้นคำตอบ = 5'],
 ['Addition/Subtraction','บวกเมทริกซ์','A=[[1,2],[3,4]], B=[[5,6],[7,8]] จงหา A+B','[[6,8],[10,12]]','1) ขนาดเท่ากัน 2×2 จึงบวกได้\n2) ตำแหน่ง (1,1): 1+5=6\n3) (1,2): 2+6=8\n4) (2,1): 3+7=10\n5) (2,2): 4+8=12'],
 ['Scalar Multiplication','คูณสเกลาร์','จงหา -2[[1,-3],[4,2]]','[[-2,6],[-8,-4]]','1) -2×1=-2\n2) -2×(-3)=6\n3) -2×4=-8\n4) -2×2=-4\n5) รวมเป็น [[-2,6],[-8,-4]]'],
 ['Matrix Multiplication','แถว × หลัก','A=[[1,2],[3,4]], B=[[5,6],[7,8]] จงหา AB','[[19,22],[43,50]]','1) (1,1)=1×5+2×7=5+14=19\n2) (1,2)=1×6+2×8=6+16=22\n3) (2,1)=3×5+4×7=15+28=43\n4) (2,2)=3×6+4×8=18+32=50'],
 ['Matrix Multiplication','ตรวจขนาด','A มีขนาด 2×3 และ B มีขนาด 3×4 ผล AB มีขนาดเท่าไร?','2×4','1) เขียน (2×3)(3×4)\n2) ตัวกลาง 3=3 → คูณได้\n3) เอาตัวนอก 2×4 → ผลลัพธ์ 2×4'],
 ['Transpose','แถวกลายเป็นหลัก','A=[[1,2,3],[4,5,6]] จงหา Aᵀ','[[1,4],[2,5],[3,6]]','1) แถวที่ 1 [1,2,3] กลายเป็นหลักที่ 1\n2) แถวที่ 2 [4,5,6] กลายเป็นหลักที่ 2\n3) จึงได้ [[1,4],[2,5],[3,6]]\n4) ขนาด 2×3 เปลี่ยนเป็น 3×2'],
 ['Determinant','Det 2×2','det([[2,3],[1,4]]) เท่ากับเท่าไร?','5','1) สูตร det = ad−bc\n2) a=2,d=4 → ad=2×4=8\n3) b=3,c=1 → bc=3×1=3\n4) 8−3=5'],
 ['Determinant','Det 2×2','det([[5,-2],[3,1]]) เท่ากับเท่าไร?','11','1) ad=5×1=5\n2) bc=(-2)×3=-6\n3) ad−bc=5−(-6)\n4) =11'],
 ['Inverse','Inverse 2×2','A=[[2,1],[1,1]] จงหา A⁻¹','[[1,-1],[-1,2]]','1) det(A)=2×1−1×1=1\n2) สูตร A⁻¹=1/det[[d,-b],[-c,a]]\n3) แทนค่า =1/1[[1,-1],[-1,2]]\n4) ได้ [[1,-1],[-1,2]]\n5) ตรวจ A·A⁻¹=I'],
 ['Inverse','ตรวจว่ามี Inverse ไหม','A=[[2,4],[1,2]] มี inverse หรือไม่?','ไม่มี','1) det=2×2−4×1=4−4=0\n2) det(A)=0\n3) เมทริกซ์ที่ det=0 เป็น singular\n4) จึงไม่มี inverse'],
 ['Cramer’s Rule','แก้ระบบสมการ','2x+y=5 และ x−y=1 จงหา x,y','x=2, y=1','1) D=|2 1; 1 -1|=2(-1)-1(1)=-3\n2) Dx=|5 1; 1 -1|=5(-1)-1(1)=-6\n3) x=Dx/D=(-6)/(-3)=2\n4) Dy=|2 5; 1 1|=2(1)-5(1)=-3\n5) y=Dy/D=(-3)/(-3)=1'],
 ['Functions','ฟังก์ชัน','f(x)=2x+3 จงหา f(4)','11','1) แทน x=4 ลงในสูตร\n2) f(4)=2(4)+3\n3) =8+3\n4) =11'],
 ['Quadratic','สมการกำลังสอง','x²−5x+6=0 จงหา x','2, 3','1) หาเลข 2 จำนวนที่คูณกันได้ 6 และบวกกันได้ -5\n2) คือ -2,-3\n3) x²−5x+6=(x−2)(x−3)\n4) ให้แต่ละวงเล็บ =0\n5) x=2 หรือ 3'],
 ['Percentage','ร้อยละ','ราคา 800 ลด 15% เหลือเท่าไร?','680','1) ส่วนลด=15% ของ 800\n2) 0.15×800=120\n3) ราคาหลังลด=800−120\n4) =680'],
 ['Exponents','เลขยกกำลัง','2³×2⁴ เท่ากับเท่าไร?','128','1) ฐานเหมือนกัน → บวกเลขชี้กำลัง\n2) 2³×2⁴=2⁷\n3) 2⁷=128'],
 ['Logarithm','ลอการิทึม','log₂8 เท่ากับเท่าไร?','3','1) ถามว่า 2 ยกกำลังอะไรได้ 8\n2) 2³=8\n3) ดังนั้น log₂8=3'],
 ['Derivative','อนุพันธ์พื้นฐาน','f(x)=x³−2x จงหา f′(x)','3x²−2','1) d/dx(x³)=3x²\n2) d/dx(-2x)=-2\n3) รวมผล → f′(x)=3x²−2'],
 ['Probability','ความน่าจะเป็น','โยนเหรียญยุติธรรม 1 ครั้ง โอกาสออกหัวเท่าไร?','1/2','1) ผลลัพธ์ทั้งหมด = {หัว,ก้อย} มี 2 แบบ\n2) สิ่งที่ต้องการ = หัว มี 1 แบบ\n3) P(หัว)=1/2'],
 ['Sequence','ลำดับเลขคณิต','3,7,11,15,... พจน์ที่ 10 เท่ากับเท่าไร?','39','1) a₁=3 และ d=4\n2) สูตร aₙ=a₁+(n−1)d\n3) a₁₀=3+9(4)\n4) =39'],
 ['Theory','ศัพท์ Matrix','ใน Aˣ, A และ x เรียกว่าอะไร?','A=ฐาน, x=เลขชี้กำลัง','1) รูป Aˣ เป็นเลขยกกำลัง\n2) A คือฐาน (base)\n3) x คือเลขชี้กำลัง (exponent)'],
 ['Theory','เงื่อนไขการคูณ','(m×n)(n×p) ผลลัพธ์มีขนาดอะไร?','m×p','1) ตรวจตัวกลาง n กับ n ต้องเท่ากัน\n2) ถ้าเท่ากันจึงคูณได้\n3) ขนาดผลลัพธ์ใช้ตัวนอก → m×p'],
 ['Theory','AB และ BA','ถ้า A และ B เป็น Matrix แล้ว AB=BA เสมอหรือไม่?','ไม่เสมอ','1) การคูณ Matrix โดยทั่วไปไม่เป็น commutative\n2) ดังนั้น AB อาจไม่เท่ากับ BA\n3) ต้องคำนวณหรือมีเงื่อนไขพิเศษจึงสรุปได้'],
 ['Theory','Determinant','ถ้า det(A)=0 แล้ว A⁻¹ มีหรือไม่?','ไม่มี','1) Inverse มีเมื่อ det(A)≠0\n2) ถ้า det(A)=0 → singular\n3) ดังนั้นไม่มี A⁻¹']
];
function workedExamples(c){c.innerHTML=`<div class="hero"><small>✏️ WORKED EXAMPLES</small><h1>โจทย์พร้อมวิธีทำแบบละเอียด</h1><p>รวมโจทย์ตัวอย่างที่เปิดดูวิธีทำทีละบรรทัดได้ทันที เน้น Matrix และหัวข้อสอบคณิตที่ใช้บ่อย</p><div class="actions"><button class="primary" onclick="randomWorked()">🎲 สุ่มโจทย์</button><button class="secondary" onclick="go('tools')">🧮 เปิดเครื่องมือคำนวณ</button></div></div><div class="grid topics" style="margin-top:18px">${WORKED_EXAMPLES.map((q,i)=>`<div class="card"><span class="tag">${q[0]}</span><h3>${q[1]}</h3><p><b>โจทย์:</b> ${q[2]}</p><div class="answer"><b>คำตอบ:</b> ${q[3]}</div><button class="secondary" onclick="toggleWorked(${i})">📖 แสดงวิธีทำละเอียด</button><div id="worked-${i}" class="feedback" style="display:none"><b>🧩 วิธีทำทีละขั้น</b><ol>${q[4].split('\\n').map(x=>`<li style="margin:8px 0">${x.replace(/^\d+\) /,'')}</li>`).join('')}</ol><div class="hint"><b>⚡ เทคนิค:</b> ${workedTip(q[0])}</div></div></div>`).join('')}</div>`;if(window.MathJax)MathJax.typesetPromise()}
function toggleWorked(i){let e=document.getElementById('worked-'+i);if(e)e.style.display=e.style.display==='none'?'block':'none'}
function randomWorked(){let i=Math.floor(Math.random()*WORKED_EXAMPLES.length);go('worked');setTimeout(()=>{toggleWorked(i);document.getElementById('worked-'+i)?.scrollIntoView({behavior:'smooth',block:'center'})},100)}
function workedTip(t){return {'Matrix Multiplication':'จำว่า แถว × หลัก และตรวจมิติด้านในก่อน','Determinant':'2×2 ใช้ ad−bc อย่าลืมเครื่องหมาย','Inverse':'หา det ก่อนเสมอ ถ้า det=0 จบ: ไม่มี inverse','Cramer’s Rule':'หา D ก่อน แล้วค่อย Dx/Dy','Functions':'แทนค่า x อย่างเป็นขั้นตอน','Quadratic':'แยกตัวประกอบแล้วตั้งแต่ละวงเล็บเป็นศูนย์','Derivative':'ดึงเลขชี้กำลังลงหน้า แล้วลดกำลัง 1','Percentage':'แปลง % เป็นทศนิยมก่อนคูณ','Theory':'โจทย์ทฤษฎีให้จับ keyword ก่อนคำนวณ'}[t]||'เขียนข้อมูล → เลือกสูตร → แทนค่า → คำนวณ → ตรวจคำตอบ'}
function mathTools(c){c.innerHTML=`<div class="hero"><small>🧮 SCIENTIFIC MATH TOOLS</small><h1>เครื่องคิดเลขวิทยาศาสตร์</h1><p>เครื่องคิดเลขสไตล์ Scientific Calculator สำหรับใช้ฝึกคณิต พร้อมฟังก์ชันตรีโกณมิติ ลอการิทึม ยกกำลัง ราก เศษส่วน และเครื่องมือคณิตทั่วไป</p></div>
<div class="scientific-wrap">
<div class="scientific-calc card">
  <div class="calc-top"><span>SCIENTIFIC</span><button class="secondary" onclick="sciClearAll()">AC</button></div>
  <div class="calc-display"><div id="sciMemory" class="calc-memory"></div><input id="sciExpr" autocomplete="off" inputmode="decimal" placeholder="0" onkeydown="sciKey(event)"><div id="sciResult" class="calc-result">0</div></div>
  <div class="calc-mode"><button id="degBtn" class="mode-active" onclick="sciSetAngle('DEG')">DEG</button><button id="radBtn" onclick="sciSetAngle('RAD')">RAD</button><button onclick="sciToggleInv()">INV</button><button onclick="sciMemoryStore()">M+</button><button onclick="sciMemoryRecall()">MR</button><button onclick="sciMemoryClear()">MC</button></div>
  <div class="sci-grid">
   <button onclick="sciFn('sin(")">sin</button><button onclick="sciFn('cos(")">cos</button><button onclick="sciFn('tan(")">tan</button><button onclick="sciFn('asin(")">sin⁻¹</button><button onclick="sciFn('acos(")">cos⁻¹</button><button onclick="sciFn('atan(")">tan⁻¹</button>
   <button onclick="sciFn('log(")">log</button><button onclick="sciFn('ln(")">ln</button><button onclick="sciFn('sqrt(")">√</button><button onclick="sciFn('cbrt(")">∛</button><button onclick="sciFn('abs(")">|x|</button><button onclick="sciFn('fact(")">x!</button>
   <button onclick="sciFn('Math.PI')">π</button><button onclick="sciFn('Math.E')">e</button><button onclick="sciFn('^2')">x²</button><button onclick="sciFn('^3')">x³</button><button onclick="sciFn('^')">xʸ</button><button onclick="sciFn('1/(')">1/x</button>
   <button onclick="sciFn('(')">(</button><button onclick="sciFn(')')">)</button><button onclick="sciFn('%')">%</button><button onclick="sciFn('10^')">10ˣ</button><button onclick="sciFn('2^')">2ˣ</button><button onclick="sciBack()">⌫</button>
   <button onclick="sciFn('7')">7</button><button onclick="sciFn('8')">8</button><button onclick="sciFn('9')">9</button><button onclick="sciFn('/')">÷</button><button onclick="sciFn('Ans')">Ans</button><button onclick="sciClear()">C</button>
   <button onclick="sciFn('4')">4</button><button onclick="sciFn('5')">5</button><button onclick="sciFn('6')">6</button><button onclick="sciFn('*')">×</button><button onclick="sciFn('(-')">(−</button><button onclick="sciFn('Math.floor(')">floor</button>
   <button onclick="sciFn('1')">1</button><button onclick="sciFn('2')">2</button><button onclick="sciFn('3')">3</button><button onclick="sciFn('-')">−</button><button onclick="sciFn('Math.ceil(')">ceil</button><button onclick="sciFn('Math.round(')">round</button>
   <button onclick="sciFn('0')">0</button><button onclick="sciFn('.')">.</button><button onclick="sciFn('+')">+</button><button class="equals" onclick="sciEvaluate()">=</button><button onclick="sciToggleSign()">±</button><button onclick="sciFn('rand()')">RAND</button>
  </div>
</div>
<div class="calc-tools">
<div class="card"><h3>🧮 สมการกำลังสอง</h3><p class="muted">ax² + bx + c = 0</p><div class="matrix-input"><input id="qa" type="number" placeholder="a"><input id="qb" type="number" placeholder="b"><input id="qc" type="number" placeholder="c"></div><div id="quadResult" class="answer">คำตอบจะแสดงที่นี่</div><button class="primary" onclick="calcQuadratic()">แก้สมการ + แสดงขั้นตอน</button></div>
<div class="card"><h3>📊 เปอร์เซ็นต์</h3><div class="matrix-input"><input id="baseP" type="number" placeholder="จำนวน"><input id="rateP" type="number" placeholder="%"></div><div id="pctResult" class="answer">ผลลัพธ์</div><div class="actions"><button class="primary" onclick="calcPercent('add')">บวก %</button><button class="secondary" onclick="calcPercent('sub')">ลด %</button></div></div>
<div class="card"><h3>🔢 เศษส่วน</h3><div class="matrix-input"><input id="fa" type="number" placeholder="เศษ 1"><input id="fb" type="number" placeholder="ส่วน 1"><input id="fc" type="number" placeholder="เศษ 2"><input id="fd" type="number" placeholder="ส่วน 2"></div><div id="fracResult" class="answer">ผลลัพธ์</div><button class="primary" onclick="calcFraction()">บวกเศษส่วน</button></div>
</div></div>`}
function matrixCalc(c){c.innerHTML=`<div class="head"><div><h2>🧮 Matrix Calculator 2×2</h2><div class="muted">เครื่องมือเฉพาะของ Matrix — det, Inverse และ Transpose พร้อมขั้นตอน</div></div><button class="secondary" onclick="go('matrix')">← กลับ Matrix</button></div><div class="card matrix-calc-page"><div class="matrix-input"><input id="tm11" type="number" placeholder="a"><input id="tm12" type="number" placeholder="b"><input id="tm21" type="number" placeholder="c"><input id="tm22" type="number" placeholder="d"></div><div id="tmResult" class="answer">ใส่ Matrix แล้วเลือกเครื่องมือ</div><div class="actions"><button class="primary" onclick="toolDet()">det(A)</button><button class="secondary" onclick="toolInv()">A⁻¹</button><button class="secondary" onclick="toolTranspose()">Aᵀ</button></div></div>`;if(window.MathJax)MathJax.typesetPromise()}

function sciVal(){return document.getElementById('sciExpr')}
let sciAngle='DEG',sciInv=false,sciMemory=0,sciAns=0;
function sciFn(x){let e=sciVal();if(x==='Ans')x=String(sciAns);e.value+=x;e.focus()}
function sciClear(){sciVal().value='';document.getElementById('sciResult').textContent='0'}
function sciClearAll(){sciClear();sciMemory=0;document.getElementById('sciMemory').textContent=''}
function sciBack(){let e=sciVal();e.value=e.value.slice(0,-1);e.focus()}
function sciToggleSign(){let e=sciVal();if(e.value)e.value=e.value.startsWith('-(')?e.value.slice(2,-1):'-('+e.value+')';e.focus()}
function sciSetAngle(a){sciAngle=a;document.getElementById('degBtn').classList.toggle('mode-active',a==='DEG');document.getElementById('radBtn').classList.toggle('mode-active',a==='RAD')}
function sciToggleInv(){sciInv=!sciInv;toast(sciInv?'INV mode: ใช้ sin⁻¹/cos⁻¹/tan⁻¹':'กลับสู่ฟังก์ชันปกติ')}
function sciMemoryStore(){try{sciMemory=Number(sciResultValue());document.getElementById('sciMemory').textContent='M = '+sciMemory}catch{}}
function sciMemoryRecall(){sciFn(String(sciMemory))}
function sciMemoryClear(){sciMemory=0;document.getElementById('sciMemory').textContent=''}
function sciResultValue(){return Number(document.getElementById('sciResult').textContent.replace(/,/g,''))}
function fact(n){if(n<0||!Number.isInteger(n)||n>170)throw Error('factorial');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function cbrt(x){return Math.cbrt(x)}
function rand(){return Math.random()}
function sciEvaluate(){let raw=sciVal().value.trim();if(!raw)return;sciInv=false;try{let e=raw.replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,'Math.PI').replace(/\^/g,'**');e=e.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');const toRad=x=>sciAngle==='DEG'?x*Math.PI/180:x;const fromRad=x=>sciAngle==='DEG'?x*180/Math.PI:x;const sin=x=>Math.sin(toRad(x)),cos=x=>Math.cos(toRad(x)),tan=x=>Math.tan(toRad(x));const asin=x=>fromRad(Math.asin(x)),acos=x=>fromRad(Math.acos(x)),atan=x=>fromRad(Math.atan(x));const log=x=>Math.log10(x),ln=x=>Math.log(x),sqrt=x=>Math.sqrt(x),abs=x=>Math.abs(x);if(!/^[0-9+\-*/().,%\sA-Za-z_\[\]]+$/.test(e)||/[;{}=`<>]/.test(e))throw Error();let v=Function('sin','cos','tan','asin','acos','atan','log','ln','sqrt','abs','fact','cbrt','rand','Math','return '+e)(sin,cos,tan,asin,acos,atan,log,ln,sqrt,abs,fact,cbrt,rand,Math);if(!Number.isFinite(v))throw Error();sciAns=v;document.getElementById('sciResult').textContent=Number(v.toPrecision(12)).toString();}catch{document.getElementById('sciResult').textContent='Error';}}
function sciKey(ev){if(ev.key==='Enter'||ev.key==='='){ev.preventDefault();sciEvaluate()}else if(ev.key==='Escape')sciClear()}
function toolVals(){return ['tm11','tm12','tm21','tm22'].map(n)}
function toolDet(){let[a,b,c,d]=toolVals(),x=a*d-b*c;document.getElementById('tmResult').innerHTML=`det(A) = ad − bc<br>= ${a}×${d} − ${b}×${c}<br>= ${a*d} − ${b*c}<br><b>= ${x}</b>`}
function toolInv(){let[a,b,c,d]=toolVals(),det=a*d-b*c,e=document.getElementById('tmResult');if(det===0){e.innerHTML='<b>ไม่มี A⁻¹</b><br>det(A)=0';return}e.innerHTML=`det(A) = ${det}<br>A⁻¹ = 1/${det} [[${d}, ${-b}], [${-c}, ${a}]]`}
function toolTranspose(){let[a,b,c,d]=toolVals();document.getElementById('tmResult').innerHTML=`A = [[${a}, ${b}], [${c}, ${d}]]<br>Aᵀ = <b>[[${a}, ${c}], [${b}, ${d}]]</b>`}

function n(id){return Number(document.getElementById(id).value)}
function calculateBasic(){let e=document.getElementById('calcExpr').value.trim().replace(/\^/g,'**');try{if(!/^[0-9+\-*/().\s*]+$/.test(e))throw Error();document.getElementById('calcResult').textContent=Function('return '+e)()}catch{document.getElementById('calcResult').textContent='กรุณาใส่นิพจน์ตัวเลขที่ถูกต้อง'}}
function calcDet2(){let a=n('m11'),b=n('m12'),c=n('m21'),d=n('m22');document.getElementById('detResult').innerHTML=`${a}×${d} − ${b}×${c} = ${a*d} − ${b*c} = <b>${a*d-b*c}</b>`}
function calcInv2(){let a=n('i11'),b=n('i12'),c=n('i21'),d=n('i22'),det=a*d-b*c;let e=document.getElementById('invResult');if(det===0){e.innerHTML='<b>❌ ไม่มี Inverse</b><br>เพราะ det = 0';return}e.innerHTML=`det = ${a}×${d}−${b}×${c} = <b>${det}</b><br>A⁻¹ = 1/${det} [[${d}, ${-b}], [${-c}, ${a}]]`}
function calcQuadratic(){let a=n('qa'),b=n('qb'),c=n('qc'),D=b*b-4*a*c,e=document.getElementById('quadResult');if(a===0){e.textContent='a ต้องไม่เป็น 0';return}if(D<0){e.innerHTML=`Δ=${D} → ไม่มีคำตอบจริง`;return}let x1=(-b+Math.sqrt(D))/(2*a),x2=(-b-Math.sqrt(D))/(2*a);e.innerHTML=`Δ=b²−4ac=${D}<br>x₁=<b>${x1}</b> · x₂=<b>${x2}</b>`}
function calcPercent(mode){let x=n('baseP'),r=n('rateP'),v=x*r/100,res=mode==='add'?x+v:x-v;document.getElementById('pctResult').innerHTML=`${x} × ${r}% = ${v}<br>คำตอบ = <b>${res}</b>`}
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a||1}
function calcFraction(){let a=n('fa'),b=n('fb'),c=n('fc'),d=n('fd');if(!b||!d){document.getElementById('fracResult').textContent='ส่วนต้องไม่เป็น 0';return}let num=a*d+c*b,den=b*d,g=gcd(num,den);document.getElementById('fracResult').innerHTML=`(${a}/${b}) + (${c}/${d}) = ${num}/${den} = <b>${num/g}/${den/g}</b>`}

function matrixDetailedSolution(q){
 const t=q.subtopic||q.topic||'';
 const common={
  'Matrix Basic':['1) อ่านขนาด m×n ก่อน','2) m = จำนวนแถว และ n = จำนวนหลัก','3) ถ้าถาม aᵢⱼ ให้ดู i=แถว, j=หลัก','4) ตรวจว่าคำตอบสอดคล้องกับรูปร่างของเมทริกซ์'],
  'Addition/Subtraction':['1) ตรวจว่า Matrix ทั้งสองมีขนาดเท่ากัน','2) จับสมาชิกตำแหน่งเดียวกัน','3) บวก/ลบทีละช่อง','4) คำตอบมีขนาดเท่าเดิม'],
  'Scalar Multiplication':['1) แยก scalar k ออกจาก Matrix','2) นำ k คูณทุกสมาชิก','3) ระวังเครื่องหมายลบ','4) ขนาด Matrix ไม่เปลี่ยน'],
  'Matrix Multiplication':['1) ดูขนาด A=m×n และ B=n×p','2) ถ้าเลขด้านในไม่เท่ากัน → คูณไม่ได้','3) ผลลัพธ์มีขนาด m×p','4) แต่ละช่อง = แถวของ A × หลักของ B แล้วรวมผลคูณ'],
  'Transpose':['1) เขียนแถวเดิมของ A','2) เปลี่ยนแถวเป็นหลัก','3) ทำครบทุกแถว','4) ขนาด m×n เปลี่ยนเป็น n×m'],
  'Determinant':['1) ตรวจว่าเป็น Square Matrix','2) ถ้า 2×2 ใช้ ad−bc','3) ถ้า 3×3 ขยายด้วย Minor/Cofactor หรือวิธีที่เรียน','4) ตรวจเครื่องหมาย โดยเฉพาะ +−+'],
  'Adjoint':['1) หา Minor ทุกตำแหน่ง','2) ใส่เครื่องหมาย Cofactor','3) สร้าง Cofactor Matrix','4) Transpose เพื่อได้ adj(A)'],
  'Inverse':['1) ตรวจว่าเป็น Square Matrix','2) หา det(A)','3) ถ้า det(A)=0 → ไม่มี inverse','4) ถ้า 2×2 ใช้สูตร inverse หรือ adj(A)/det(A)','5) ตรวจโดยคูณ A·A⁻¹ ควรได้ I'],
  "Cramer's Rule":['1) จัดสัมประสิทธิ์เป็น coefficient matrix A','2) หา D=det(A)','3) สร้าง Dₓ, Dᵧ,... โดยแทนคอลัมน์ด้วยค่าคงที่','4) ใช้ x=Dₓ/D, y=Dᵧ/D,...','5) ต้องมี D≠0 สำหรับสูตรนี้']
 };
 let steps=common[t]||['1) อ่านว่าโจทย์ถามอะไร','2) ระบุสูตร/นิยามที่ตรงกับโจทย์','3) ตรวจเงื่อนไขก่อนคำนวณ','4) ทำทีละขั้น','5) ตรวจคำตอบกับสูตรและขนาดอีกครั้ง'];
 if(Array.isArray(q.detailedSteps)&&q.detailedSteps.length)steps=q.detailedSteps;
 return `<div id="detailSolution" class="feedback" style="display:none;margin-top:12px"><b>📖 วิธีทำละเอียด</b><ol>${steps.map(x=>`<li style="margin:9px 0">${x}</li>`).join('')}</ol>${q.explanation?`<div class="hint"><b>🎯 ทำไมข้อนี้ถึงตอบ ${esc(q.answer)}?</b><br>${q.explanation}</div>`:''}${q.commonMistake?`<div class="hint"><b>⚠️ ตรวจจุดพลาด:</b> ${q.commonMistake}</div>`:''}</div>`;
}
function toggleDetailSolution(){const x=document.getElementById('detailSolution');if(x)x.style.display=x.style.display==='none'?'block':'none';if(window.MathJax)MathJax.typesetPromise()}

function quizView(c){clearInterval(timer);let q=quiz.pool[quiz.i];c.innerHTML=`<div class="quiz"><div class="muted">ข้อ ${quiz.i+1}/${quiz.pool.length} · ${q.topic} · <span id="clock"></span></div><div class="bar" style="margin-top:8px"><i style="width:${pct(quiz.i,quiz.pool.length)}%"></i></div><div class="card" style="margin-top:15px"><div class="tag">${q.difficulty}</div><div class="q">${q.question}</div><div class="choices">${q.choices.map((x,i)=>`<button class="choice ${quiz.selected===i?"sel":""}" ${quiz.answered?"disabled":""} onclick="choose(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join("")}</div>${quiz.answered?(quiz.mode==="mock"||quiz.mode==="matrixmock"?`<div class="feedback"><b>คำตอบถูกบันทึกแล้ว</b><br><span class="muted">Mock Exam จะเฉลยหลังสอบจบ</span></div>`:`<div class="feedback"><b class="${quiz.selectedAnswer===q.answer?"success":"danger"}">${quiz.selectedAnswer===q.answer?"✓ ถูกต้อง":"✗ ยังไม่ถูก"}</b><br><b>เฉลย: ${esc(q.answer)}</b><br>${q.explanation||""}<br><b>🧠 วิธีคิด:</b> ${q.hint||"เริ่มจากนิยาม/เงื่อนไขก่อนคำนวณ"}<br><b>⚡ วิธีลัด:</b> ${q.shortcut||"ตรวจสูตรและเงื่อนไขสำคัญก่อน"}<br><b>⚠️ จุดที่มักผิด:</b> ${q.commonMistake||"ตรวจเครื่องหมายและขั้นตอนอีกครั้ง"}${q.topic==="เมทริกซ์"?matrixDetailedSolution(q):""}<br><button class="secondary" onclick="toggleDetailSolution()">📖 แสดงวิธีทำละเอียด</button></div>`):`<div id="h"></div>`}<div class="quizfoot"><button class="secondary" onclick="go('practice')">ออก</button>${!quiz.answered?`<button class="secondary" onclick="hint()">💡 Hint</button><button class="primary" onclick="submit()">ส่งคำตอบ</button>`:`<button class="primary" onclick="nextQ()">${quiz.i+1<quiz.pool.length?"ข้อถัดไป →":"ดูผลลัพธ์"}</button>`}</div></div></div>`;if(quiz.seconds)startTimer()}
function choose(i){if(!quiz.answered){quiz.selected=i;quizView(document.getElementById("content"))}}
function submit(){if(quiz.selected===null){toast("เลือกคำตอบก่อนนะ");return}let q=quiz.pool[quiz.i],a=q.choices[quiz.selected];quiz.selectedAnswer=a;quiz.answered=true;state.attempts++;if(a===q.answer){state.correct++;quiz.score++;addXP(15)}else{if(!state.wrong.includes(q.id))state.wrong.push(q.id);state.mistakes[q.topic]=(state.mistakes[q.topic]||0)+1;addXP(5)}if(q.topic==="เมทริกซ์"){state.attemptsMatrix=(state.attemptsMatrix||0)+1;if(a===q.answer)state.correctMatrix=(state.correctMatrix||0)+1;else{state.wrongMatrix=state.wrongMatrix||[];if(!state.wrongMatrix.includes(q.id))state.wrongMatrix.push(q.id);state.matrixMistakes=state.matrixMistakes||{};state.matrixMistakes[q.subtopic||q.topic]=(state.matrixMistakes[q.subtopic||q.topic]||0)+1} }save();quizView(document.getElementById("content"))}
function nextQ(){if(quiz.i+1>=quiz.pool.length){if(quiz.mode==="matrixmock"){let pctv=pct(quiz.score,quiz.pool.length);state.matrixHistory=state.matrixHistory||[];state.matrixHistory.push({date:new Date().toLocaleString("th-TH"),score:quiz.score,pct:pctv});save();go("matrixresult");return}state.history.push({date:new Date().toLocaleString("th-TH"),score:`${quiz.score}/${quiz.pool.length}`});save();go("progress");return}if(quiz.mode==="matrixdrill"&&quiz.startTime){state.matrixSpeed=state.matrixSpeed||[];state.matrixSpeed.push(Math.min(100,Math.round((Date.now()-quiz.startTime)/1000/quiz.pool.length*4)));save()}quiz.i++;quiz.selected=null;quiz.answered=false;quiz.selectedAnswer=null;quizView(document.getElementById("content"))}
function hint(){let q=quiz.pool[quiz.i];let el=document.getElementById("h");if(el)el.innerHTML=`<div class="hint">💡 <b>Hint:</b> ${q.hint}<br><small>ยังไม่เฉลย ลองคิดเองก่อน</small></div>`}
function startTimer(){clearInterval(timer);if(!quiz.endTime)quiz.endTime=Date.now()+quiz.seconds*1000;timer=setInterval(()=>{let x=Math.max(0,quiz.endTime-Date.now()),m=Math.floor(x/60000),s=Math.floor(x/1000)%60,e=document.getElementById("clock");if(e)e.textContent=`⏱ ${m}:${String(s).padStart(2,"0")}`;if(x<=0){clearInterval(timer);toast("หมดเวลา");if(quiz.mode==="matrixmock"){finishMatrixMock(false)}else{quiz.i=quiz.pool.length-1;quiz.answered=true;quiz.selected=null;quizView(document.getElementById("content"))}}},250)}
function memorize(c){c.innerHTML=`<div class="head"><div><h2>🧠 Memorize</h2><div class="muted">Active Recall + Spaced Repetition</div></div><span class="tag">จำแล้ว ${state.formulaKnown.length}/${FORMULAS.length}</span></div><div class="card flash"><div><div class="flashq" id="fq"></div><div id="fa"></div><div class="actions" style="justify-content:center"><button class="primary" onclick="reveal()">แสดงคำตอบ</button></div><div class="ratings" id="ratings" style="display:none;margin-top:15px"><button onclick="rate('good')">😄 จำได้ดี</button><button onclick="rate('ok')">🙂 จำได้</button><button onclick="rate('weak')">😐 ไม่ค่อยได้</button><button onclick="rate('bad')">😵 จำไม่ได้</button></div></div></div><div class="head"><h2>📖 Formula Bank</h2></div><div class="list">${FORMULAS.map(f=>`<div class="card"><b>${f[1]}</b><div class="formul">${f[2]}</div><div class="muted">${f[3]} · ใช้เมื่อ: ${f[4]}</div><p>🧠 ${f[5]}</p><button class="secondary" onclick="mark('${f[0]}')">${state.formulaKnown.includes(f[0])?"⭐ จำแล้ว":"☆ จำแล้ว"}</button></div>`).join("")}</div>`;flashIndex=Math.floor(Math.random()*FORMULAS.length);flashShown=false;updateFlash()}
function updateFlash(){let f=FORMULAS[flashIndex],q=document.getElementById("fq"),a=document.getElementById("fa");if(!q)return;q.textContent=`“${f[1]} — สูตรคืออะไร?”`;a.innerHTML=flashShown?`<div class="answer">${f[2]}</div><div class="muted">${f[4]}</div>`:"";document.getElementById("ratings").style.display=flashShown?"flex":"none"}
function reveal(){flashShown=true;updateFlash()}
function rate(r){let id=FORMULAS[flashIndex][0];if(r==="good"||r==="ok"){if(!state.formulaKnown.includes(id))state.formulaKnown.push(id)}else{state.formulaKnown=state.formulaKnown.filter(x=>x!==id);state.review.push({id,next:Date.now()+86400000})}save();addXP(r==="good"?20:10);go("memorize")}
function mark(id){if(state.formulaKnown.includes(id))state.formulaKnown=state.formulaKnown.filter(x=>x!==id);else state.formulaKnown.push(id);save();render()}
function mock(c){c.innerHTML=`<div class="head"><h2>🎯 Mock Exam</h2></div><div class="card"><div class="grid choicegrid"><label>จำนวนข้อ<select id="mc"><option>10</option><option selected>20</option><option>30</option><option>50</option></select></label><label>เวลา (นาที)<select id="mt"><option>15</option><option selected>30</option><option>45</option><option>60</option></select></label></div><p class="muted">ไม่มีเฉลยระหว่างสอบ หลังจบระบบจะบันทึกผลและนำไปวิเคราะห์</p><button class="primary" onclick="startMock()">🎯 เริ่ม Mock Exam</button></div><div class="head"><h2>ประวัติ</h2></div>${state.history.length?`<table class="table"><tr><th>วันที่</th><th>คะแนน</th></tr>${state.history.slice(-10).reverse().map(x=>`<tr><td>${x.date}</td><td>${x.score}</td></tr>`).join("")}</table>`:"<div class='empty'>ยังไม่มีประวัติ</div>"}`}
function startMock(){quiz={mode:"mock",pool:shuffle(QUESTIONS).slice(0,+document.getElementById("mc").value),i:0,selected:null,answered:false,score:0,seconds:+document.getElementById("mt").value*60};go("quiz")}
function last(c){c.innerHTML=`<div class="hero"><small>🔥 LAST MINUTE MATH</small><h1>มีเวลาเหลือเท่าไร?</h1><p>จัดลำดับสิ่งที่คุ้มค่าต่อคะแนนก่อนเข้าห้องสอบ</p></div><div class="grid quick" style="margin-top:18px">${[5,10,15,30,60,120].map(n=>`<button class="card" onclick="plan(${n})"><div class="emoji">⚡</div><b>${n<60?n+" นาที":n/60+" ชั่วโมง"}</b><div class="muted">สร้างแผน</div></button>`).join("")}</div><div id="plan"></div>`}
function plan(n){let weak=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1])[0]?.[0]||"หัวข้อออกสอบบ่อย";let steps=n<=10?[["0–2","สูตรสำคัญ"],["2–7","โจทย์ออกสอบบ่อย"],["7–10","ทบทวนข้อผิด"]]:n<=30?[["0–5","ทบทวนสูตร"],["5–15","โจทย์ออกสอบบ่อย"],["15–25","โจทย์จับเวลา"],["25–30","ทบทวนข้อผิด"]]:[["0–10","Formula Active Recall"],["10–35","โจทย์ออกสอบบ่อย"],["35–50","แก้ข้อผิดซ้ำ"],["50–60","Mini Test"]];document.getElementById("plan").innerHTML=`<div class="head"><h2>แผน ${n} นาที</h2></div><div class="list"><div class="card"><b>🎯 จุดเน้น:</b> ${weak}</div>${steps.map(s=>`<div class="listitem"><b>${s[0]}</b><span>${s[1]}</span><button class="secondary" onclick="go('${s[1].includes("สูตร")?"memorize":"practice"}')">เริ่ม</button></div>`).join("")}</div>`}
function progress(c){let acc=pct(state.correct,state.attempts),weak=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]);let ready=Math.round(acc*.4+pct(state.formulaKnown.length,FORMULAS.length)*.25+Math.min(100,state.attempts/30*100)*.2);c.innerHTML=`<div class="head"><h2>📊 Progress</h2></div><div class="card"><h2>ความพร้อมสอบ ${ready}%</h2><div class="bar"><i style="width:${ready}%"></i></div></div><div class="grid stats"><div class="card"><div class="muted">Accuracy</div><div class="num">${acc}%</div></div><div class="card"><div class="muted">XP</div><div class="num">${state.xp}</div><div class="muted">Level ${state.level}</div></div><div class="card"><div class="muted">Streak</div><div class="num">${state.streak} 🔥</div></div><div class="card"><div class="muted">สูตร</div><div class="num">${pct(state.formulaKnown.length,FORMULAS.length)}%</div></div></div><div class="head"><h2>จุดอ่อน</h2></div><div class="card">${weak.length?weak.slice(0,6).map(x=>`<div class="meterrow"><span>${x[0]}</span><div class="meter"><i style="width:${Math.min(100,x[1]/Math.max(1,state.attempts-state.correct)*100)}%"></i></div><b>${x[1]}</b></div>`).join(""):"<div class='empty'>ทำโจทย์ก่อนเพื่อให้ระบบวิเคราะห์</div>"}</div>`}
function settings(c){c.innerHTML=`<div class="head"><h2>⚙️ Settings</h2></div><div class="card"><label>ชื่อผู้เรียน<input id="sn" value="${esc(state.settings.name)}" style="padding:9px;border:1px solid #ddd;border-radius:8px"></label><br><label>เป้าหมายโจทย์/วัน<input id="sg" type="number" value="${state.settings.goal}" style="padding:9px;border:1px solid #ddd;border-radius:8px"></label><br><label>วันสอบ<input id="sd" type="date" value="${state.examDate||"2026-09-15"}" style="padding:9px;border:1px solid #ddd;border-radius:8px"></label><br><button class="primary" onclick="saveSettings()">บันทึก</button></div><div class="card" style="margin-top:15px"><b>LocalStorage</b><p class="muted">Progress, คะแนน, ข้อผิด, สูตร, Streak และ Mock history จะไม่หายเมื่อ Refresh</p><button class="secondary" onclick="resetAll()">ล้างข้อมูลทั้งหมด</button></div>`}
function saveSettings(){state.settings.name=document.getElementById("sn").value;state.settings.goal=+document.getElementById("sg").value;state.examDate=document.getElementById("sd").value||null;state.prioritySubject="เมทริกซ์";save();toast("บันทึกแล้ว");render()}
function resetAll(){if(confirm("ล้าง Progress ทั้งหมด?")){localStorage.removeItem(KEY);state=load();render();toast("รีเซ็ตแล้ว")}}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.style.cssText="position:fixed;bottom:25px;left:50%;transform:translateX(-50%);background:#111827;color:#fff;padding:11px 16px;border-radius:10px;z-index:50";setTimeout(()=>x.style.display="none",2200)}
document.addEventListener("click",e=>{let b=e.target.closest("[data-page]");if(b)go(b.dataset.page)});
document.getElementById("search").addEventListener("input",e=>{let t=e.target.value.trim().toLowerCase();if(!t){render();return}let a=QUESTIONS.filter(q=>(q.question+q.topic+q.tags.join(" ")).toLowerCase().includes(t)).slice(0,12);document.getElementById("content").innerHTML=`<div class="head"><h2>🔎 ผลค้นหา</h2></div><div class="list">${a.map(q=>`<div class="listitem"><div><b>${q.question}</b><div class="muted">${q.topic} · ${q.difficulty}</div></div><button class="secondary" onclick="one('${q.id}')">ทำข้อนี้</button></div>`).join("")||"<div class='empty'>ไม่พบผลลัพธ์</div>"}</div>`});
render();