const MATRIX_ZERO_SOURCES=[
 {name:'Project 14 (สสวท.) — เมทริกซ์ ตอน 1–2',url:'https://proj14.ipst.ac.th/m4-6-math-adv/m5-math-adv-book1/math-m5b1-010/',why:'พื้นฐานความหมาย ขนาด สมาชิก การเท่ากัน และการบวก/ลบ/คูณด้วยจำนวนจริง'},
 {name:'SciMath — สมบัติการคูณเมทริกซ์',url:'https://www.scimath.org/lessonplan/item/12215-1-5',why:'แนวคิดและสมบัติการคูณเมทริกซ์สำหรับระดับ ม.5'},
 {name:'SciMath — สมบัติของดีเทอร์มิแนนต์',url:'https://www.scimath.org/lessonplan/item/12218-1-6',why:'Determinant และสมบัติที่ใช้ในการสอบ'},
 {name:'Khan Academy — Matrices',url:'https://www.khanacademy.org/math/algebra-home/alg-matrices',why:'บทเรียนและแบบฝึกหัดภาษาอังกฤษ ตั้งแต่พื้นฐานถึง inverse'},
 {name:'Khan Academy — Matrix multiplication dimensions',url:'https://www.khanacademy.org/math/algebra-home/alg-matrices/a/matrix-multiplication-dimensions',why:'เงื่อนไขการคูณและขนาดของผลคูณ'},
 {name:'OpenStax — College Algebra',url:'https://openstax.org/books/college-algebra/pages/7-key-concepts',why:'Determinant, Cramer และสมบัติของ determinant'},
 {name:'LibreTexts — Inverse of a Matrix',url:'https://math.libretexts.org/Courses/De_Anza_College/Linear_Algebra%3A_A_First_Course/02%3A_Matrices/2.02%3A_The_Inverse_of_a_Matrix',why:'สมบัติ inverse และความสัมพันธ์กับ transpose/product'}
];
const MATRIX_ZERO_LESSONS=[
 {id:'z1',title:'Matrix คืออะไร?',short:'เมทริกซ์คือการจัดตัวเลขเป็นตารางแถวและหลัก',know:'Matrix = ตารางของสมาชิกที่จัดเป็น Row และ Column',instant:'เห็นวงเล็บเป็นตารางตัวเลข → นึกว่า “Matrix” ก่อน แล้วนับแถว × หลัก',steps:['ดูจำนวนแถวจากบนลงล่าง','ดูจำนวนหลักจากซ้ายไปขวา','เขียนขนาดเป็น rows × columns','สมาชิกแต่ละตัวเรียกว่า element/entry'],example:'A = [[2, 5, -1], [0, 4, 3]] → มี 2 แถว 3 หลัก → A เป็น 2×3',trap:'2×3 ไม่ได้หมายถึง 2 หลัก 3 แถว'},
 {id:'z2',title:'Order / Dimension และ aᵢⱼ',short:'ตำแหน่งสมาชิกอ่านเป็น “แถวที่ i หลักที่ j”',know:'A₍ᵢⱼ₎ = สมาชิกแถว i หลัก j',instant:'ตัวห้อยตัวแรก = แถว, ตัวห้อยตัวที่สอง = หลัก',steps:['หา i ก่อน = row','หา j ต่อ = column','เดินไปตำแหน่งนั้น','ค่าที่พบคือ aᵢⱼ'],example:'A=[[1,7],[3,5]] → a₂₁ = 3 เพราะแถว 2 หลัก 1',trap:'สลับ i,j เป็นข้อหลอกยอดนิยม'},
 {id:'z3',title:'ชนิดของ Matrix ที่ต้องเห็นแล้วตอบได้',short:'จำจากรูปร่าง ไม่ต้องคำนวณ',know:'Row, Column, Square, Zero, Diagonal, Scalar, Identity, Triangular, Symmetric',instant:'Square = แถวเท่าหลัก; Identity = diagonal เป็น 1 ที่เหลือ 0',steps:['นับแถวและหลัก','ตรวจว่าเป็นสี่เหลี่ยมหรือไม่','ดูเส้นทแยงหลัก','ดูสมาชิกนอกเส้นทแยง','จับชื่อชนิดที่ตรงเงื่อนไข'],example:'[[1,0,0],[0,1,0],[0,0,1]] = Identity matrix I₃',trap:'Diagonal matrix ไม่จำเป็นต้องมี diagonal เป็น 1; ถ้าเป็น 1 ทั้งหมดจึงเป็น Identity'},
 {id:'z4',title:'การเท่ากัน + บวก/ลบ',short:'ขนาดต้องเท่ากัน และทำสมาชิกตำแหน่งเดียวกัน',know:'A+B ทำได้เมื่อ A,B มีขนาดเดียวกัน',instant:'บวก/ลบ = ช่องตรงกันทำกับช่องตรงกัน',steps:['เช็ก order ของสอง Matrix','ถ้าขนาดไม่เท่ากัน → ทำไม่ได้','บวก/ลบสมาชิกตำแหน่งเดียวกัน','คงขนาดเดิม'],example:'[[1,2],[3,4]] + [[5,6],[7,8]] = [[6,8],[10,12]]',trap:'ห้ามเอาแถวหนึ่งไปบวกกับหลักหนึ่ง'},
 {id:'z5',title:'Scalar Multiplication',short:'เลขหนึ่งตัวคูณสมาชิกทุกตัว',know:'kA = นำ k คูณทุก entry ของ A',instant:'เห็น kA → คูณ k ทุกช่อง',steps:['เขียน k ไว้หน้าทุกสมาชิก','คูณทีละช่อง','เครื่องหมายลบต้องติดตามไปด้วย','ขนาด Matrix ไม่เปลี่ยน'],example:'-2[[1,-3],[4,0]] = [[-2,6],[-8,0]]',trap:'Scalar multiplication ต่างจาก matrix multiplication'},
 {id:'z6',title:'Matrix Multiplication — แถว × หลัก',short:'คูณได้เมื่อจำนวนหลักของ A = จำนวนแถวของ B',know:'(m×n)(n×p)=m×p',instant:'“ในต้องเท่ากัน นอกคือคำตอบ”',steps:['ดูขนาด A และ B','ตรวจเลขด้านในให้เท่ากัน','คำตอบใช้เลขด้านนอก','หาแต่ละช่องด้วย row ของ A dot column ของ B'],example:'(2×3)(3×4) → คูณได้ และคำตอบเป็น 2×4',trap:'AB ไม่ได้แปลว่าคูณสมาชิกตำแหน่งเดียวกัน และ AB อาจไม่เท่ากับ BA'},
 {id:'z7',title:'Transpose — แถวกลายเป็นหลัก',short:'สลับ Row ↔ Column',know:'Aᵀ เปลี่ยนตำแหน่งแถวเป็นหลัก',instant:'“หมุนมุมมอง: แถวกลายเป็นหลัก”',steps:['เอา row 1 ไปเป็น column 1','เอา row 2 ไปเป็น column 2','ทำต่อจนหมด','ขนาด m×n จะกลายเป็น n×m'],example:'[[1,2,3],[4,5,6]]ᵀ = [[1,4],[2,5],[3,6]]',trap:'Transpose ไม่ใช่การกลับเศษส่วน และไม่ใช่ inverse'},
 {id:'z8',title:'Determinant 2×2 — ad−bc',short:'ตัวเลขหนึ่งค่าที่ได้จาก Square Matrix',know:'det[[a,b],[c,d]]=ad−bc',instant:'ทแยงหลักคูณกัน − ทแยงรองคูณกัน',steps:['คูณ a×d','คูณ b×c','เอา ad ลบ bc','เช็กเครื่องหมายอีกครั้ง'],example:'det[[2,3],[1,4]]=2(4)-3(1)=5',trap:'ห้ามใช้ determinant กับ Matrix ที่ไม่เป็น square'},
 {id:'z9',title:'Determinant 3×3 — Minor/Cofactor',short:'แยกตามแถวหรือหลักด้วย Minor และ Cofactor',know:'Cofactor Cᵢⱼ = (-1)ⁱ⁺ʲ Mᵢⱼ',instant:'เครื่องหมาย cofactor 3×3 = + − + / − + − / + − +',steps:['เลือกแถว/หลักที่จะขยาย','ตัดแถว i และหลัก j ออกเพื่อได้ minor','ใส่เครื่องหมาย cofactor','คูณสมาชิกกับ cofactor แล้วรวม'],example:'ใช้แถวที่มีศูนย์หลายตัวจะลดงานได้มาก',trap:'ลืมเครื่องหมายลบของตำแหน่ง cofactor'},
 {id:'z10',title:'Inverse — เมทริกซ์ผกผัน',short:'A⁻¹ คือ Matrix ที่คูณกับ A แล้วได้ I',know:'AA⁻¹=A⁻¹A=I และต้องเป็น square + det(A)≠0',instant:'“คูณแล้วกลับไปเป็น I”',steps:['ตรวจว่า A เป็น square','หา det(A)','ถ้า det=0 → ไม่มี inverse','ถ้า det≠0 → หา inverse ตามวิธีที่เรียน'],example:'A=[[a,b],[c,d]] → A⁻¹=1/(ad−bc)[[d,-b],[-c,a]]',trap:'det=0 ห้ามหารด้วย 0 และห้ามสับสน Aᵀ กับ A⁻¹'},
 {id:'z11',title:'Adjoint / Adjugate',short:'Transpose ของ cofactor matrix',know:'adj(A)=Cᵀ',instant:'หา Cofactor matrix ก่อน แล้ว transpose',steps:['หา minor แต่ละตำแหน่ง','ใส่ cofactor signs','รวมเป็น cofactor matrix C','transpose C → adj(A)'],example:'สูตร inverse แบบ determinant: A⁻¹ = adj(A)/det(A)',trap:'Adjoint ไม่ใช่แค่ transpose ของ A'},
 {id:'z12',title:'ระบบสมการ + AX=B + Cramer',short:'เปลี่ยนระบบสมการให้เป็นภาษาของ Matrix',know:'AX=B → X=A⁻¹B เมื่อ A invertible; Cramer x=Dₓ/D',instant:'จัดสัมประสิทธิ์เป็น A, ตัวแปรเป็น X, ค่าคงที่เป็น B',steps:['จัดสมการให้ตัวแปรอยู่ในลำดับเดียวกัน','สร้าง A,X,B','ตรวจ det(A)≠0 ถ้าจะใช้ inverse','เลือกวิธี inverse หรือ Cramer ตามโจทย์'],example:'2x+y=5, x-y=1 → A=[[2,1],[1,-1]], X=[[x],[y]], B=[[5],[1]]',trap:'สลับลำดับตัวแปรใน A แล้วคำตอบจะผิดทั้งชุด'}
];
function matrixZero(c){const done=state.matrixZeroDone||[];c.innerHTML=`<div class="hero"><small>🧠 MATRIX ZERO → EXAM READY</small><h1>เริ่มเรียนเมทริกซ์ตั้งแต่ 0</h1><p>เข้าใจ → เห็นแล้วตอบได้ → ลงมือทำ → วิเคราะห์ข้อผิด → พร้อมสอบ</p><div class="actions"><button class="primary" onclick="matrixZeroLesson(0)">🚀 เริ่มจาก 0</button><button class="secondary" onclick="go('matrix')">← Matrix Dashboard</button></div></div><div class="card" style="margin-top:18px"><div class="head"><h2>ความคืบหน้า</h2><b>${done.length}/${MATRIX_ZERO_LESSONS.length}</b></div><div class="bar"><i style="width:${pct(done.length,MATRIX_ZERO_LESSONS.length)}%"></i></div><p>เป้าหมาย: อ่านโจทย์ทฤษฎีแล้ว “เห็นคำสำคัญ → นึกหลัก → ตอบได้ทันที”</p></div><div class="grid topics">${MATRIX_ZERO_LESSONS.map((l,i)=>`<div class="card"><span class="tag">STEP ${i+1}</span><h3>${l.title}</h3><p>${l.short}</p><p class="muted">🧠 ${l.instant}</p><button class="secondary" onclick="matrixZeroLesson(${i})">เรียนบทนี้</button></div>`).join('')}</div><div class="card" style="margin-top:18px"><h2>🌏 แหล่งอ้างอิงที่ใช้สังเคราะห์</h2><p class="muted">เนื้อหาในบทเรียนนี้สรุปและเรียบเรียงใหม่ ไม่คัดลอกข้อความจากแหล่งใดแหล่งหนึ่ง</p>${MATRIX_ZERO_SOURCES.map(s=>`<div class="listitem"><div><b>${s.name}</b><div class="muted">${s.why}</div></div><a class="secondary" href="${s.url}" target="_blank" rel="noopener">เปิดแหล่งอ้างอิง ↗</a></div>`).join('')}</div>`}

function matrixWorkedExample(id){
 const E={
 z1:['1) นับจำนวนแถว: มี 2 แถว','2) นับจำนวนหลัก: มี 3 หลัก','3) เขียนขนาด = 2×3','4) ดังนั้น A เป็นเมทริกซ์ 2×3'],
 z2:['1) อ่าน a₂₁ โดยดูตัวห้อยตัวแรก = แถว 2','2) ตัวห้อยตัวที่สอง = หลัก 1','3) ไปตำแหน่งแถว 2 หลัก 1','4) ได้ค่า 3 ดังนั้น a₂₁ = 3'],
 z3:['1) Matrix มี 3×3 → เป็น Square','2) นอกเส้นทแยงหลักเป็น 0 ทั้งหมด → เป็น Diagonal','3) บนเส้นทแยงหลักเป็น 1 ทั้งหมด → เป็น Identity','4) จึงเป็นทั้ง Square + Diagonal + Identity'],
 z4:['1) ทั้งสองเมทริกซ์เป็น 2×2 จึงบวกได้','2) ช่อง (1,1): 1+5=6','3) ช่อง (1,2): 2+6=8','4) ช่อง (2,1): 3+7=10','5) ช่อง (2,2): 4+8=12','6) คำตอบ = [[6,8],[10,12]]'],
 z5:['1) เอา −2 คูณสมาชิกทุกช่อง','2) −2×1 = −2 และ −2×(−3)=6','3) −2×4 = −8 และ −2×0=0','4) ได้ [[−2,6],[−8,0]]'],
 z6:['1) A ขนาด 2×3 และ B ขนาด 3×4','2) เลขด้านใน 3 กับ 3 เท่ากัน → คูณได้','3) เลขด้านนอก 2 กับ 4 → ผลลัพธ์เป็น 2×4','4) แต่ละช่องคำนวณด้วย “แถวของ A × หลักของ B”'],
 z7:['1) Row 1 = [1,2,3] → Column 1 = [1,2,3]ᵀ','2) Row 2 = [4,5,6] → Column 2 = [4,5,6]ᵀ','3) จึงได้ [[1,4],[2,5],[3,6]]','4) ขนาด 2×3 เปลี่ยนเป็น 3×2'],
 z8:['1) ระบุ a=2,b=3,c=1,d=4','2) คูณทแยงหลัก: ad = 2×4 = 8','3) คูณทแยงรอง: bc = 3×1 = 3','4) ลบ: ad−bc = 8−3 = 5','5) ดังนั้น det(A)=5'],
 z9:['1) เลือกแถว/หลักสำหรับขยาย โดยเลือกที่มีศูนย์ถ้ามี','2) ตัดแถวและหลักของสมาชิกนั้นออก → เหลือ 2×2','3) หา determinant ของ 2×2 ที่เหลือ = Minor','4) ใส่เครื่องหมายตามตาราง + − + / − + − / + − +','5) คูณสมาชิกเดิมกับ Cofactor แล้วบวกผลทั้งหมด'],
 z10:['1) ตรวจว่า A เป็น Square','2) หา det(A)','3) ถ้า det(A)=0 → ห้ามหา inverse เพราะต้องหารด้วย 0','4) ถ้าเป็น 2×2 ให้สลับ a,d และเปลี่ยนเครื่องหมาย b,c','5) หารทุกสมาชิกด้วย det(A)','6) ตรวจได้ด้วย A·A⁻¹ = I'],
 z11:['1) หา Minor ทุกตำแหน่ง','2) เปลี่ยน Minor เป็น Cofactor ด้วยเครื่องหมาย +−+ / −+− / +−+','3) รวม Cofactor เป็นเมทริกซ์ C','4) transpose C','5) ผลที่ได้คือ adj(A)=Cᵀ'],
 z12:['1) จัดตัวแปรให้เรียงเหมือนกันทุกสมการ เช่น x,y','2) สัมประสิทธิ์ของ x,y → A','3) ตัวแปร → X','4) ค่าคงที่ด้านขวา → B','5) ได้ AX=B','6) ถ้า det(A)≠0 ใช้ X=A⁻¹B หรือเลือก Cramer ตามโจทย์']
 }; return E[id]||['อ่านโจทย์','ระบุสูตร/เงื่อนไขที่เกี่ยวข้อง','ทำทีละขั้นและตรวจคำตอบกับเงื่อนไขอีกครั้ง'];
}
function toggleMatrixSolution(){const x=document.getElementById('matrixSolution');if(x)x.style.display=x.style.display==='none'?'block':'none'}

function matrixZeroLesson(i){const l=MATRIX_ZERO_LESSONS[i];const next=i+1;state.matrixZeroDone=state.matrixZeroDone||[];if(!state.matrixZeroDone.includes(i)){state.matrixZeroDone.push(i);save()}const practice={question:`ข้อทดสอบเร็ว: ${l.title} — จากคำอธิบายนี้ ข้อใดคือหลักที่ต้องจำ?`,choices:[l.know,l.instant,'ต้องคำนวณทุกครั้ง','ไม่มีเงื่อนไข'],answer:l.know,explanation:`หลักสำคัญของบทนี้คือ: ${l.know}`};c=document.getElementById('content');c.innerHTML=`<div class="head"><div><span class="tag">STEP ${i+1}/${MATRIX_ZERO_LESSONS.length}</span><h2>${l.title}</h2><div class="muted">${l.short}</div></div><button class="secondary" onclick="go('matrixzero')">← สารบัญ</button></div><div class="grid" style="grid-template-columns:1.25fr .75fr"><div><div class="card"><h3>🧠 เข้าใจให้เห็นภาพ</h3><p style="font-size:18px">${l.know}</p><div class="card" style="margin-top:12px"><b>👀 มองแล้วตอบทันที</b><p>${l.instant}</p></div></div><div class="card"><h3>🧩 วิธีคิดก่อนลงมือทำ</h3><ol>${l.steps.map(x=>`<li style="margin:10px 0">${x}</li>`).join('')}</ol><div class="hint"><b>⚡ สูตรการคิด:</b> อย่ารีบคำนวณ → ระบุสิ่งที่โจทย์ถาม → เช็กเงื่อนไข → ทำทีละขั้น → ตรวจคำตอบ</div></div><div class="card"><h3>✏️ ตัวอย่าง + วิธีทำละเอียด</h3><p style="font-size:18px">${l.example}</p><button class="secondary" onclick="toggleMatrixSolution()">📖 แสดง/ซ่อนวิธีทำทีละขั้น</button><div id="matrixSolution" class="feedback" style="display:block;margin-top:12px"><b>🧩 วิธีทำแบบละเอียด</b><ol>${matrixWorkedExample(l.id).map(x=>`<li style="margin:9px 0">${x}</li>`).join('')}</ol><div class="hint"><b>🎯 สิ่งที่ต้องมองให้ออก:</b> ${l.instant}</div></div></div><div class="card"><h3>⚠️ จุดหลอก</h3><p>${l.trap}</p></div></div><div><div class="card"><span class="tag">จำก่อนสอบ</span><h3>🎯 One-Liner</h3><p style="font-size:20px;font-weight:800">${l.instant}</p></div><div class="card"><h3>📝 ทดสอบทันที</h3><p>${practice.question}</p>${practice.choices.map((x,j)=>`<button class="choice" onclick="this.parentElement.querySelectorAll('.choice').forEach(b=>b.disabled=true);this.classList.add('${x===practice.answer?'correct':'wrong'}');document.getElementById('zp').innerHTML='${x===practice.answer?'✅ ถูกต้อง — ': '❌ ยังไม่ใช่ — '} ${practice.explanation}'">${String.fromCharCode(65+j)}. ${x}</button>`).join('')}<div id="zp" class="feedback"></div></div><div class="card"><h3>🔁 ทำซ้ำ</h3><button class="primary" onclick="matrixZeroLesson(${i})">ทบทวนบทนี้</button>${next<MATRIX_ZERO_LESSONS.length?`<button class="secondary" onclick="matrixZeroLesson(${next})">บทถัดไป →</button>`:`<button class="secondary" onclick="go('matrixmock')">🎯 ไป Mock Exam</button>`}</div></div></div>`;if(window.MathJax)MathJax.typesetPromise()}
